#!/usr/bin/env sh
set -euf

# shellcheck disable=SC2154
if [ -d "$f" ] && mountpoint -q -- "$f" 1>/dev/null 2>/dev/null; then
  cat "/proc/mounts" | while read -r line; do
    case "$line" in
      *" ${f} "*)
        exec lf -remote "send ${id} set user_fmnt \"${line%% *}\""
      ;;
    esac
  done
else
  exec lf -remote "send ${id} set user_fmnt \"\""
fi
