#!/usr/bin/env sh
set -euf

dev=""

# shellcheck disable=SC2154
if [ -d "$f" ] && mountpoint -q -- "$f" 1>/dev/null 2>/dev/null; then
  dev="$(set +e; grep " ${f} " "/proc/mounts"; set -e)"
  dev="${dev%% *}"
fi

# shellcheck disable=SC2154
lf -remote "send ${id} set user_fmnt \"${dev}\""
