#!/usr/bin/env sh
set -eu

rulerfmt="%a| %p| \033[7;31m %m \033[0m| \033[7;33m %c \033[0m| \033[7;35m %s \033[0m| \033[7;34m %f \033[0m| %i/%t %P"

mnt_str=""
mode_str=""

# shellcheck disable=SC2154
if [ -d "$f" ] && mountpoint -q -- "$f" 1>/dev/null 2>/dev/null; then
  dev="$(set +e; grep " ${f} " "/proc/mounts" | cut -d" " -f1; set -e)"

  if [ "$dev" ]; then
    mnt_str="\033[0;90m${dev}\033[0m| "
  fi
fi

# shellcheck disable=SC2154
if [ "$lf_user_quittimer" != "true" ]; then
  mode_str="notimer |"
fi

# shellcheck disable=SC2154
if [ "$lf_mode" != "normal" ]; then
  mode_str="${lf_mode} |"
fi

rulerfmt_updated="${mode_str}${mnt_str}${rulerfmt}"

# shellcheck disable=SC2154
if [ "$lf_rulerfmt" != "$rulerfmt_updated" ]; then
  lf -remote "send ${id} set rulerfmt \"${rulerfmt_updated}\""
fi
