#!/usr/bin/env sh
set -euf
IFS_="$IFS"
NL="
"

files="${fv:-"$fx"}"

printf 'Selected to extract:\n%s\n' "$files"

IFS="$NL"
for f in $files; do 
  IFS="$IFS_"
  echo "${NL}---${NL}${f}${NL}"
  aunpack --explain --subdir "$f"
done
IFS="$IFS_"
