#!/usr/bin/env sh
set -eu

"${XDG_DATA_HOME:-"$HOME/.local/share"}/lf/quittimer" 0</dev/null 1>/dev/null 2>/dev/null & disown

"${XDG_CONFIG_HOME:-"$HOME/.config"}/lf/exec/_set-ratios" 0</dev/null 1>/dev/null 2>/dev/null & disown
"${XDG_CONFIG_HOME:-"$HOME/.config"}/lf/exec/_set-title" 0</dev/null 1>/dev/null 2>/dev/null & disown
"${XDG_CONFIG_HOME:-"$HOME/.config"}/lf/exec/_set-rulerfmt" 0</dev/null 1>/dev/null 2>/dev/null & disown

lf -remote "send ${id} reload" 0</dev/null 1>/dev/null 2>/dev/null & disown
