#!/usr/bin/env sh
set -eu
IFS_="$IFS"

"${XDG_CONFIG_HOME:-"${HOME}/.config"}/lf/exec/_heartbeat" 0</dev/null 1>/dev/null 2>/dev/null & disown

files="${fv:-"$fx"}"
first_file="$(echo "$files" | head -n1)"
mime="$(file --mime-type --brief "$first_file")"

in_pager() {
  IFS="
"
  for file in $files; do
    IFS="$IFS_"
    set -- "$@" "$file"
  done
  IFS="$IFS_"

  exec $PAGER "$@"
}

in_opener() {
  IFS="
"
  for f in $files; do
    IFS="$IFS_"
    nohup "$OPENER" "$f" 0</dev/null 1>/dev/null 2>/dev/null & disown
  done
  IFS="$IFS_"
}

open_with() {
  exec lf -remote "send ${id} push :open-with<space>"
}

case $mime in
  application/octet-stream)
    open_with
  ;;
  text/rtf)
  ;;
  text/*|application/xml|application/*json*|application/xhtml*|application/javascript|application/x-httpd-php|application/x-wine-extension-ini|application/x-mswinurl|application/x-subrip|application/x-awk|inode/x-empty)
    in_pager
  ;;
  # Archive types that 'als' recognizes.
  application/gzip|application/java-archive|application/vnd.debian.binary-package|application/vnd.ms-cab-compressed|application/vnd.rar|application/x-7z-compressed|application/x-ace|application/x-alz|application/x-archive|application/x-arj|application/x-bzip1|application/x-bzip1-compressed-tar|application/x-bzip2|application/x-bzip2-compressed-tar|application/x-compress|application/x-compressed-tar|application/x-cpio|application/x-lha|application/x-lrzip|application/x-lzip|application/x-lzip-compressed-tar|application/x-lzma-compressed-tar|application/x-lzma|application/x-lzop|application/x-rpm|application/x-tar|application/x-tarz|application/x-tzo|application/x-xz|application/x-xz-compressed-tar|application/zip)
    if [ "${f##*.}" = "edoc" ]; then
      (trap "" "HUP"; PATH=${PATH}:/usr/bin:/usr/lib/eparakstitajs3/bin /usr/bin/eparakstitajs3 "$f") 0</dev/null 1>/dev/null 2>/dev/null & disown
      exit
    fi

    in_pager
  ;;
  application/x-iso9660-image)
    in_pager
  ;;
esac

if [ "$(command -v "xdg-mime")" ] && [ -z "$(xdg-mime query default "$mime")" ]; then
  open_with
fi

in_opener 0</dev/null 1>/dev/null 2>/dev/null & disown
