#!/usr/bin/env sh
set -eu
IFS_="$IFS"

"${XDG_CONFIG_HOME:-"${HOME}/.config"}/lf/exec/_heartbeat" 0</dev/null 1>/dev/null 2>/dev/null & disown

files="${fv:-"$fx"}"

  IFS="
"

for f in $files; do
  IFS="$IFS_"
  nohup "$OPENER" "$f" 0</dev/null 1>/dev/null 2>/dev/null & disown
done
IFS="$IFS_"
