#!/usr/bin/env sh
set -eu

set +e
: > "/tmp/${USER}_lf_heartbeat/${id}" 2> "/dev/null"
set -e

files="${fv:-"$fx"}"

mime="$(file --mime-type --brief "$(readlink -f "$(echo "$files" | head -n1)")")"

IFS="
"
case $mime in
  application/octet-stream)
    exec lf -remote "send ${id} push :open-with<space>"
  ;;
  text/rtf)
  ;;
  text/*|application/xml|application/*json*|application/xhtml*|application/javascript|application/x-httpd-php|application/x-wine-extension-ini|application/x-mswinurl|application/x-subrip|application/x-awk|inode/x-empty)
    exec $PAGER $files
  ;;
  application/gzip|application/java-archive|application/vnd.debian.binary-package|application/vnd.ms-cab-compressed|application/vnd.rar|application/x-7z-compressed|application/x-ace|application/x-alz|application/x-archive|application/x-arj|application/x-bzip1|application/x-bzip1-compressed-tar|application/x-bzip2|application/x-bzip2-compressed-tar|application/x-compress|application/x-compressed-tar|application/x-cpio|application/x-lha|application/x-lrzip|application/x-lzip|application/x-lzip-compressed-tar|application/x-lzma-compressed-tar|application/x-lzma|application/x-lzop|application/x-rpm|application/x-tar|application/x-tarz|application/x-tzo|application/x-xz|application/x-xz-compressed-tar|application/zip)
    # Archive types that 'als' recognizes.
    exec $PAGER $files
  ;;
  application/x-iso9660-image)
    exec $PAGER $files
  ;;
esac

if [ "$(command -v "xdg-mime")" ] && [ -z "$(xdg-mime query default "$mime")" ]; then
  exec lf -remote "send ${id} push :open-with<space>"
fi

for f in $files; do
  nohup $OPENER "$f" 0</dev/null 1>/dev/null 2>/dev/null & disown
done
