#!/usr/bin/env sh
set -eu

call() { exec lf -remote "send ${id} set ratios ${1}"; }

if [ "$lf_width" -le "40"  ]; then call "100:1";    fi
if [ "$lf_width" -le "80"  ]; then call "3:4";      fi
if [ "$lf_width" -le "120" ]; then call "2:4:4";    fi
if [ "$lf_width" -le "160" ]; then call "1:3:5:5";  fi
                                   call "1:2:4:7:8"
