#!/usr/bin/env sh

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway &

gsettings set "org.gnome.desktop.interface" cursor-size "42"

# .Xresources

## xrdb

xrdb -retain -load "${XDG_CONFIG_HOME:-$HOME/.config}/xresources/.Xresources"

pathf_xresources_local="${XDG_CONFIG_HOME:-$HOME/.config}/xresources/local.Xresources"
[ -f "$pathf_xresources_local" ] && xrdb -retain -override "$pathf_xresources_local"

## xsettingsd

"${XDG_DATA_HOME:-$HOME/.local/share}/xsettingsd/init" &

# Starting VirtualBox guest service

VBoxClient-all &

# Running EeasyEffects audio effects interface

[ -z "$(pidof easyeffects)" ] && easyeffects --gapplication-service &

# TODO: local

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/sway/init.local" ] && exec "${XDG_CONFIG_HOME:-$HOME/.config}/sway/init.local"
