#!/usr/bin/env sh

# GUI environment variables

. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/gui.sh"

# gsettings

gsettings "set" "org.gnome.desktop.interface" "cursor-size" "${GUI_CURSOR_SIZE}"
gsettings "set" "org.gnome.desktop.interface" "scaling-factor" "${GUI_SCALING_FACTOR}"
gsettings "set" "org.gnome.desktop.interface" "text-scaling-factor" "${GUI_SCALING_FACTOR}"

# .Xresources

## xrdb

xrdb -retain -load "${XDG_CONFIG_HOME:-$HOME/.config}/xresources/.Xresources"

pathf_xresources_local="${XDG_CONFIG_HOME:-$HOME/.config}/xresources/local.Xresources"
[ -f "$pathf_xresources_local" ] && xrdb -retain -override "$pathf_xresources_local"

## xsettingsd

"${XDG_DATA_HOME:-$HOME/.local/share}/xsettingsd/init" &

# Starting VirtualBox guest service

VBoxClient-all &

# Running EeasyEffects audio effects interface

[ -z "$(pidof easyeffects)" ] && easyeffects --gapplication-service &

# Local settings

pathf_init_local="${XDG_CONFIG_HOME:-$HOME/.config}/sway/init.local"
[ -f "$pathf_init_local" ] && exec "$pathf_init_local"
