#!/usr/bin/env sh

user="$(whoami)"

# GUI environment variables

. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/gui.sh"

# ----

# gsettings

"${XDG_CONFIG_HOME:-$HOME/.config}/gsettings/init"

# .Xresources

## xrdb

xrdb -retain -load "${XDG_CONFIG_HOME:-$HOME/.config}/xresources/.Xresources"

pathf_xresources_local="${XDG_CONFIG_HOME:-$HOME/.config}/xresources/local.Xresources"
[ -f "$pathf_xresources_local" ] && xrdb -retain -override "$pathf_xresources_local"

## xsettingsd

"${XDG_DATA_HOME:-$HOME/.local/share}/xsettingsd/init" &

# swayidle, swaylock

color_bg_swaylock="$(echo "${GUI_COLOR_BACKGROUND:-#000000}" | cut -c2-)"

killall -u "$user" "swayidle"
swayidle -w \
  timeout "60" "swaylock -u -f -c ${color_bg_swaylock}; swaymsg \"output * dpms off\"" \
  resume "swaymsg \"output * dpms on\" && sway-audio-idle-inhibit &" \
  before-sleep "swaylock -u -f -c ${color_bg_swaylock}" &

## Idle inhibiting on audio I/O

killall -u "$user" "sway-audio-idle-inhibit"
sway-audio-idle-inhibit &

# Starting VirtualBox guest service

VBoxClient-all &

# Running EeasyEffects audio effects interface

[ -z "$(pidof easyeffects)" ] && easyeffects --gapplication-service &

# Local settings

pathf_post_init_local="${XDG_CONFIG_HOME:-$HOME/.config}/sway/post_init_local"
[ -f "$pathf_post_init_local" ] && exec "$pathf_post_init_local"
