#!/usr/bin/env sh

# gsettings

"${XDG_CONFIG_HOME:-$HOME/.config}/gsettings/init"

# .Xresources

## xrdb

xrdb -retain -load "${XDG_CONFIG_HOME:-$HOME/.config}/xresources/.Xresources"

pathf_xresources_local="${XDG_CONFIG_HOME:-$HOME/.config}/xresources/local.Xresources"
[ -f "$pathf_xresources_local" ] && xrdb -retain -override "$pathf_xresources_local"

## xsettingsd

"${XDG_DATA_HOME:-$HOME/.local/share}/xsettingsd/init" &

# swayidle, swaylock

"${XDG_CONFIG_HOME:-$HOME/.config}/swayidle/init" &

# Starting VirtualBox guest service

VBoxClient-all &

# Running EeasyEffects audio effects interface

[ -z "$(pidof easyeffects)" ] && easyeffects --gapplication-service &

# Local settings

pathf_init_local="${XDG_CONFIG_HOME:-$HOME/.config}/sway/post_init.local"
[ -f "$pathf_init_local" ] && exec "$pathf_init_local"
