#!/usr/bin/env sh

# gsettings

"${XDG_CONFIG_HOME:-$HOME/.config}/gsettings/init"

# .Xresources

## xrdb

xrdb -retain -load "${XDG_CONFIG_HOME:-$HOME/.config}/xresources/.Xresources"

pathf_xresources_local="${XDG_CONFIG_HOME:-$HOME/.config}/xresources/local.Xresources"

if [ -f "$pathf_xresources_local" ]; then
  xrdb -retain -override "$pathf_xresources_local"
fi

## xsettingsd

"${XDG_DATA_HOME:-$HOME/.local/share}/xsettingsd/init" &

# swayidle, swaylock

idle_manager "start" &

# Starting VirtualBox guest service

VBoxClient-all &

# Polkit authentication agent

if [ -z "$(pidof "polkit-gnome-authentication-agent-1")" ]; then
  /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Running EeasyEffects audio effects interface

if [ -z "$(pidof easyeffects)" ]; then
  easyeffects --gapplication-service &
fi

# Local settings

pathf_post_init_local="${XDG_CONFIG_HOME:-$HOME/.config}/sway/post_init_local"

if [ -f "$pathf_post_init_local" ]; then
  exec_always "$pathf_post_init_local"
fi
