#!/usr/bin/env sh

[ "$BLOCK_BUTTON" ] && case "$BLOCK_BUTTON" in
  "1"|"3")
    cmd="echo -n \"\033]0;Battery information\007\"; acpi -i | ${PAGER}"
    $TERMINAL -e "$SHELL" -c "$cmd" 1>/dev/null 2>/dev/null & disown
    ;;
  "4") brightnessctl -q set "+2%" ;;
  "5") brightnessctl -q set "2%-" ;;
esac

for battery in /sys/class/power_supply/BAT?*; do
  [ -n "${capacity+x}" ] && printf " "

  capacity="$(cat "${battery}/capacity" 2>&1)"
  status="$(cat "${battery}/status" 2>&1)"

  case "$status" in
    "Full")
      label="Battery full"
      printf "%s" "$label"
      ;;
    "Discharging")
      label="Battery discharging"

      if [ "$capacity" -gt 25 ]; then
        printf "%s, %s%%" "$label" "$capacity"
      else
        printf "%s, %s %d%%" "$label" "⚠️" "$capacity"
      fi
      ;;
    "Charging")
      label="Battery charging"
      printf "%s, %s%%" "$label" "$capacity"
      ;;
    "Not charging")
      label="Battery not charging"
      printf "%s, %s %d%%" "$label" "⚠️" "$capacity"
      ;;
    "Unknown")
      label="Battery state unknown"
      printf "%s, %s %d%%" "$label" "⚠️" "$capacity"
      ;;
    *) exit "1" ;;
  esac
done && printf "\\n"
