#!/usr/bin/env sh
set -eu

if [ "${BLOCK_BUTTON:-""}" ]; then
  case "$BLOCK_BUTTON" in
    "4")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/temp_no_mouse_warping_container" "workspace" "prev_on_output" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "5")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/temp_no_mouse_warping_container" "workspace" "next_on_output" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
  esac
fi

if ! rfkill -rn -o "TYPE" | grep -xq "bluetooth"; then
  exit "0"
fi

controller_is_on="0" dev_count="0"

controller_id="$(bluetoothctl "list" 2> "/dev/null" | grep "\[default\]" | cut -f2 -d" ")"

if [ "$controller_id" ]; then
  dev_count="$(set +e; bluetoothctl "devices" "Connected" 2> "/dev/null" | grep -c "^Device "; set -e)"

  if bluetoothctl show "$controller_id" 2> "/dev/null" | grep -q "PowerState: on"; then
    controller_is_on="1"
  fi
fi

if [ "${BLOCK_BUTTON:-""}" ]; then
  reload() {
    if [ "${signal-""}" ]; then
      (sleep "${1:-"0.5"}"; pkill "-SIGRTMIN+${signal}" "i3blocks") 1> "/dev/null" 2> "/dev/null" & disown
    fi
  }

  case "$BLOCK_BUTTON" in
    "1")
      blueman-manager 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "3")
      case "$controller_is_on" in
        "0")
          rfkill "unblock" "bluetooth" 1> "/dev/null" 2> "/dev/null" & disown
          echo "Enabling Bluetooth...
Enabling Bluet."
          reload "5"
        ;;
        "1")
          rfkill "block" "bluetooth" 1> "/dev/null" 2> "/dev/null" & disown
          echo "Disabling Bluetooth...
Disabling Bluet."
          reload
        ;;
      esac
    ;;
  esac
fi

case "$dev_count" in
  "0")
    case "$controller_is_on" in
      "0")
        echo "Bluetooth off
Bluet. off"
      ;;
      "1")
        echo "Bluetooth on
Bluet. on"
      ;;
    esac
  ;;
  "1")
    echo "${dev_count} Bluetooth device
${dev_count} Bluet. dev."
  ;;
  *)
    echo "${dev_count} Bluetooth devices
${dev_count} Bluet. dev."
  ;;
esac
