#!/usr/bin/env sh
set -eu

if ! rfkill -rn -o "TYPE" | grep -xq "bluetooth"; then
  exit "0"
fi

controller_id="" controller_is_on="0" dev_count="0"

controller_id="$(bluetoothctl "list" 2> "/dev/null" | grep "\[default\]" | cut -f2 -d" ")"

if [ "$controller_id" ]; then
  dev_count="$(bluetoothctl "devices" "Connected" 2> "/dev/null" | wc -l)"

  if bluetoothctl show "$controller_id" 2> "/dev/null" | grep -q "PowerState: on"; then
    controller_is_on="1"
  fi
fi

if [ "${BLOCK_BUTTON:-""}" ]; then
  reload() {
    if [ "${signal-""}" ]; then
      (sleep "${1:-0.5}"; pkill "-SIGRTMIN+${signal}" i3blocks) 1> "/dev/null" 2> "/dev/null" & disown
    fi
  }

  case "$BLOCK_BUTTON" in
    "1")
      blueman-manager 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "3")
      case "$controller_is_on" in
        "0")
          rfkill "unblock" "bluetooth" 1> "/dev/null" 2> "/dev/null" & disown
          echo "Enabling Bluetooth..."
          reload "5"
        ;;
        "1")
          rfkill "block" "bluetooth" 1> "/dev/null" 2> "/dev/null" & disown
          echo "Disabling Bluetooth..."
          reload
        ;;
      esac
    ;;
  esac
fi

case "$dev_count" in
  "0")
    case "$controller_is_on" in
      "0")
        echo "Bluetooth disabled"
      ;;
      "1")
        echo "Bluetooth enabled"
      ;;
    esac
  ;;
  "1")
    echo "${dev_count} Bluetooth device"
  ;;
  "*")
    echo "${dev_count} Bluetooth devices"
  ;;
esac
