#!/usr/bin/env sh
set -eu

connectivity="$(nmcli networking connectivity)"

if [ -z "$connectivity" ]; then
  exit "0"
fi

label_disabling="Disabling connectivity...
Disabling conn.k."
label_enabling="Enabling connectivity...
Enabling conn.k."
label_full="Network connected
Net. connected"
label_none="Network disconnected
Net. disconnected"
label_portal="Network connected (portal)
Net. connected (portal)"
label_limited="Network connected (limited)
Net. connected (limited)"
label_unknown="Network connectivity unknown
Net. conn.k. unknown"
label_other="Network connectivity status: ${connectivity}
Net. conn.k. status: ${connectivity}"

if [ "${BLOCK_BUTTON:-""}" ]; then
  reload() {
    if [ "${signal-""}" ]; then
      (sleep "${1:-"0.5"}"; pkill "-SIGRTMIN+${signal}" "i3blocks") 1> "/dev/null" 2> "/dev/null" & disown
    fi
  }

  case "$BLOCK_BUTTON" in
    "1")
      cmd="sleep \"0.5\"; nmtui"
      $TERMINAL -e "$SHELL" -c "$cmd" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "3")
      case "$connectivity" in
        "full"|"portal"|"limited") 
          nmcli networking off 1> "/dev/null" 2> "/dev/null" & disown
          reload
          exec echo "$label_disabling"
        ;;
        *)
          nmcli networking on 1> "/dev/null" 2> "/dev/null" & disown
          reload "2"
          exec echo "$label_enabling"
        ;;
      esac
    ;;
  esac 
fi

case "$connectivity" in
  "full") echo "$label_full";;
  "none") echo "$label_none";;
  "portal") echo "$label_portal";;
  "limited") echo "$label_limited";;
  "unknown") echo "$label_unknown";;
  *) echo "$label_other";;
esac
