#!/usr/bin/env sh

connectivity="$(nmcli networking connectivity)"

[ "$connectivity" ] && {
  label_disabling="Disabling connectivity..."
  label_enabling="Enabling connectivity..."
  label_full="Network connected"
  label_none="Network disconnected"
  label_portal="Network connected (portal)"
  label_limited="Network connected (limited)"
  label_unknown="Network connectivity unknown"
  label_other="Network connectivity status: ${connectivity}"

  [ "$BLOCK_BUTTON" = "1" ] && {
    cmd="sleep \"0.5\"; nmtui"
    $TERMINAL -e "$SHELL" -c "$cmd" 1>/dev/null 2>/dev/null & disown
  } 

  [ "$BLOCK_BUTTON" = "3" ] && {
    case "$connectivity" in
      "full"|"portal"|"limited") echo "$label_disabling";;
      "none"|"unknown") echo "$label_enabling";;
      *) echo "$label_enabling";;
    esac

    if [ "$connectivity" = "none" ] || [ "$connectivity" = "unknown" ]; then
      nmcli networking on
    else
      nmcli networking off
    fi
  }

  case $connectivity in
    "full") echo "$label_full";;
    "none") echo "$label_none";;
    "portal") echo "$label_portal";;
    "limited") echo "$label_limited";;
    "unknown") echo "$label_unknown";;
    *) echo "$label_other";;
  esac
}
