#!/usr/bin/env sh
set -eu

if [ "${BLOCK_BUTTON:-""}" ]; then
  case "$BLOCK_BUTTON" in
    "1"|"3")
      $TERMINAL -e "$SHELL" -c "calcurse" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
  esac
fi

date "+%A — %-d. %B
%a, %-d. %b." | sed -e 's/./\u&/' -e 's/ //g'
