#!/usr/bin/env sh
set -eu

status="$(idle_manager_status)"

if [ "${BLOCK_BUTTON:-""}" ]; then
  reload() {
    [ "$signal" ] && {
      (sleep "0.5"; pkill "-SIGRTMIN+${signal}" i3blocks) 1> "/dev/null" 2> "/dev/null" & disown
    }
  }

  _idle_lock() {
    echo "Idle lock"
    idle_lock 1> "/dev/null" 2> "/dev/null" & disown
    exit
  }

  _idle_manager_start() {
    echo "Starting the idle manager..."
    idle_manager_start 1> "/dev/null" 2> "/dev/null" & disown
    reload
    exit
  }

  _idle_manager_stop() {
    echo "Stopping the idle manager..."
    idle_manager_stop 1> "/dev/null" 2> "/dev/null" & disown
    reload
    exit
  }

  case "$BLOCK_BUTTON" in
    "1") case "$status" in
        "started") _idle_lock ;;
        "stopped") _idle_manager_start ;;
      esac
    ;;
    "3") case "$status" in
        "started") _idle_manager_stop ;;
        "stopped") _idle_manager_start ;;
      esac
    ;;
  esac
fi

case "$status" in
  "started") echo "Idle lock" ;;
  "stopped") echo "Idle mgr. inactive" ;;
esac
