#!/usr/bin/env sh

status="$(idle_manager_status)"

[ "$BLOCK_BUTTON" ] && {
  _screen_lock() {
    echo "Idle lock"
    exec screen_lock 1>/dev/null 2>/dev/null & disown
  }

  _idle_manager_enable() {
    echo "Starting the idle manager..."
    exec idle_manager_enable 1>/dev/null 2>/dev/null & disown
  }

  _idle_manager_disable() {
    echo "Stopping the idle manager..."
    exec idle_manager_disable 1>/dev/null 2>/dev/null & disown
  }

  case "$BLOCK_BUTTON" in
    "1") case "$status" in
        "enabled") _screen_lock ;;
        "disabled") _idle_manager_enable ;;
      esac
    ;;
    "3") case "$status" in
        "enabled") _idle_manager_disable ;;
        "disabled") _idle_manager_enable ;;
      esac
    ;;
  esac
}

case "$status" in
  "enabled") echo "Idle lock" ;;
  "disabled") echo "Idle mgr. inactive" ;;
esac
