#!/usr/bin/env sh
set -eu

msg_paused="Media paused
Paused"
msg_playing="Media playing
Playing"
msg_stopped="Media stopped
Stopped"

case "$(set +e; playerctl status 2> "/dev/null"; set -e)" in
  "Playing")
    if [ "${BLOCK_BUTTON:-""}" ]; then
      case "$BLOCK_BUTTON" in
        "1")
           playerctl pause 1> "/dev/null" 2> "/dev/null" & disown
           message="$msg_paused"
        ;;
        "3")
           playerctl stop 1> "/dev/null" 2> "/dev/null" & disown
           message="$msg_stopped"
        ;;
        "4")
           playerctl position "5+" 1> "/dev/null" 2> "/dev/null" & disown
        ;;
        "5")
           playerctl position "5-" 1> "/dev/null" 2> "/dev/null" & disown
        ;;
      esac
    fi
    message="${message:-"$msg_playing"}"
  ;;
  "Paused")
    if [ "${BLOCK_BUTTON:-""}" ]; then
      case $BLOCK_BUTTON in
        "1")
           playerctl play 1> "/dev/null" 2> "/dev/null" & disown
           message="$msg_playing"
        ;;
        "3")
           playerctl stop 1> "/dev/null" 2> "/dev/null" & disown
           message="$msg_stopped"
        ;;
      esac
    fi
    message="${message:-"$msg_paused"}"
  ;;
  "Stopped")
    if [ "${BLOCK_BUTTON:-""}" ]; then
      case $BLOCK_BUTTON in
        "1"|"3")
          playerctl play 1> "/dev/null" 2> "/dev/null" & disown
          message="$msg_playing"
        ;;
      esac
    fi
    message="${message:-"$msg_stopped"}"
  ;;
  *)
    exit "0"
  ;;
esac

echo "$message"
