#!/usr/bin/env sh

fstab_mounts="$(grep -v -e "^#" -e "^$" < "/etc/fstab")"
fstab_mounts_mpts="$(echo "$fstab_mounts" | awk '{ print $2 }')"

active_mounts="$(grep -v -P " \/(sys|run|dev|proc|tmp|var)(/| )" < "/proc/mounts")"
active_mounts_mpts="$(echo "$active_mounts" | awk '{ print $2 }')"

rsd_mounts=""

ifs_old="$IFS"; IFS="
"

for i in $active_mounts_mpts; do
  echo "$fstab_mounts_mpts" | grep -xq "$i" || {
    count="$(("$count" + "1"))"
    rsd_mounts="$rsd_mounts
- $(echo "$active_mounts" | grep " $i ")"
  }
done

IFS="$ifs_old"

[ "$count" ] && {
  [ "$BLOCK_BUTTON" = "1" ] || [ "$BLOCK_BUTTON" = "3" ] && {
    title="Removable storage devices mounted"
    cmd="echo -n \"\033]0;${title}\007\"; echo \"${title}:${rsd_mounts}\" | ${PAGER}"

    $TERMINAL -e "$SHELL" -c "$cmd" 1>/dev/null 2>/dev/null & disown
  }

  [ "$count" = "1" ] && echo "$count device mounted" && exit
  echo "$count devices mounted"
}
