#!/usr/bin/env sh

fstab_mounts="$(cat "/etc/fstab" | grep -v -e "^#" -e "^$" | awk '{ print $2 }')"
current_mounts="$(cat "/proc/mounts" | grep -v -P " \/(sys|run|dev|proc|tmp)(/| )" | awk '{ print $2 }')"

IFS=$'\n'
for i in $current_mounts; do
  [ "$(printf "$fstab_mounts" | grep -x "$i")" ] || { num="$(("$num" + "1"))"; }
done

[ "$num" ] && echo "$num RSD"

# TODO: compare by device UUID
