#!/usr/bin/env sh

LABEL_WAYLAND="${LABEL_WAYLAND:-On Wayland}"
LABEL_X11="${LABEL_X11:-On X11}"

REPORT_WAYLAND="${REPORT_WAYLAND:-1}"
REPORT_X11="${REPORT_X11:-1}"

[ "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && {
   [ "$REPORT_X11" = "1" ] && exec echo "$LABEL_X11"
   exit
}

[ "$WAYLAND_DISPLAY" ] && {
  [ "$REPORT_WAYLAND" = "1" ] && exec echo "$LABEL_WAYLAND"
  exit
}

exit "1"
