#!/usr/bin/env sh
set -eu

if [ "${BLOCK_BUTTON:-""}" ]; then
  case "$BLOCK_BUTTON" in
    "2")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/new_workspace" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "4")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/temp_no_mouse_warping_container" "workspace" "prev_on_output" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "5")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/temp_no_mouse_warping_container" "workspace" "next_on_output" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
  esac
fi

if systemctl is-active --quiet smb; then
  if [ "${BLOCK_BUTTON:-""}" ] && [ "$BLOCK_BUTTON" = "3" ]; then
    cmd="echo \"\033]0;Stop SMB service\007\"; systemctl stop smb; read"
    $TERMINAL -e "$SHELL" -c "$cmd" 1> "/dev/null" 2> "/dev/null" & disown
  fi

  echo "SMB on"
fi
