#!/usr/bin/env sh

systemctl is-active --quiet smb && {
  [ "$button" = "3" ] && {
    win_title="\033]0;Stop SMB service\007"
    $TERMINAL -e "$SHELL" -c "echo -n \"$win_title\"; systemctl stop smb; read"
  }

  echo "SMB active"
}
