#!/usr/bin/env sh
set -eu

if [ "${BLOCK_BUTTON:-""}" ]; then
  case "$BLOCK_BUTTON" in
    "1")
      easyeffects 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "2")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/new_workspace" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "3")
      if ! pidof -q "wpctl"; then
        wpctl "set-mute" "@DEFAULT_SINK@" "toggle"
      fi
    ;;
    "4")
      if ! pidof -q "wpctl"; then
        wpctl "set-volume" "@DEFAULT_SINK@" "1%+"
        sound_notify "@DEFAULT_SINK@" 1> "/dev/null" 2> "/dev/null" & disown
      fi
    ;;
    "5")
      if ! pidof -q "wpctl"; then
        wpctl "set-volume" "@DEFAULT_SINK@" "1%-"
        sound_notify "@DEFAULT_SINK@" 1> "/dev/null" 2> "/dev/null" & disown
      fi
    ;;
  esac
fi

status="$(wpctl "get-volume" "@DEFAULT_SINK@")"

if [ "$status" ]; then
  vol_float="${status##Volume: }"
  vol_float="${vol_float%% *}"
  vol_int="$(awk "BEGIN{print 100 * ${vol_float}}")"
  muted="${status##Volume: * }"
  muted="${muted##Volume: *}"

  SUFFIX="${SUFFIX:-""}"

  echo "Volume ${vol_int}%${muted:+, MUTE}${SUFFIX}
Vol. ${vol_int}%${muted:+, MUTE}${SUFFIX}"
fi

exit "0"
