#!/usr/bin/env sh

systemctl is-active --quiet sshd && {
  [ "$BLOCK_BUTTON" = "3" ] && {
    win_title="\033]0;Stop SSHD service\007"
    $TERMINAL -e "$SHELL" -c "echo -n \"$win_title\"; systemctl stop sshd; read"
  }

  exec echo "SSHD active"
}

exit "0"
