#!/usr/bin/env sh
set -eu

if [ "${BLOCK_BUTTON:-""}" ]; then
  case "$BLOCK_BUTTON" in
    "1"|"3")
      cmd="timezone | \${PAGER}"
      $TERMINAL -e "$SHELL" -c "$cmd" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "2")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/new_workspace" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "4")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/temp_no_mouse_warping_container" "workspace" "prev_on_output" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "5")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/temp_no_mouse_warping_container" "workspace" "next_on_output" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
  esac
fi

date "+%-H:%M %Z"
