#!/usr/bin/env sh
set -eu
IFS_="$IFS"

if [ "${BLOCK_BUTTON:-""}" ]; then
  case "$BLOCK_BUTTON" in
    "2")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/new_workspace"
    ;;
    "4")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/temp_no_mouse_warping_container" "workspace" "prev_on_output" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
    "5")
      "${XDG_DATA_HOME:-$HOME/.local/share}/i3/temp_no_mouse_warping_container" "workspace" "next_on_output" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
  esac
fi

ups_devices="$(upsc -l 2> "/dev/null")"

if [ -z "$ups_devices" ]; then
  exit "0"
fi

if [ "${BLOCK_BUTTON:-""}" ]; then
  case "$BLOCK_BUTTON" in
    "1"|"3")
      cmd="echo \"\033]0;UPS information\007\"; ups_info | ${PAGER}"
      $TERMINAL -e "$SHELL" -c "$cmd" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
  esac
fi

i="0"

IFS="
"

for name in $ups_devices; do
  IFS="$IFS_"

  i="$((i+1))"

  status="$(set +e; upsc "$name" "ups.status" 2> "/dev/null"; set -e)"
  charge="$(set +e; upsc "$name" "battery.charge" 2> "/dev/null"; set -e)"

  status_charge=""
  status_charge_short=""

  if [ "$charge" ]; then
    if [ "$charge" -gt "98" ]; then
      status_charge="battery full"
      status_charge_short="full"
    elif [ "$charge" -gt "25" ]; then
      status_charge="${charge}%"
      status_charge_short="${charge}%"
    else
      status_charge="⚠️ ${charge}%"
      status_charge_short="⚠️ ${charge}%"
    fi
  fi

  case "$status" in
    "OL")
      info="UPS${status_charge:+" ${status_charge}"}
UPS${status_charge_short:+" ${status_charge_short}"}"
    ;;
    "")
      info="UPS disconnected
UPS disconn."
    ;;
    *)
      info="UPS: ${status}${status_charge:+", ${status_charge}"}
UPS ${status}${status_charge_short:+", ${status_charge_short}"}"
    ;;
  esac
done

IFS="$IFS_"

if [ "$info" ]; then
  echo "$info" | pr -"$i" -t -s' '
fi
