#!/usr/bin/env sh
set -eu
IFS_="$IFS"

ups_devices="$(upsc -l 2> "/dev/null")"

if [ -z "$ups_devices" ]; then
  exit "0"
fi

if [ "${BLOCK_BUTTON:-""}" ]; then
  case "$BLOCK_BUTTON" in
    "1"|"3")
      cmd="echo \"\033]0;UPS information\007\"; ups_info | ${PAGER}"
      $TERMINAL -e "$SHELL" -c "$cmd" 1> "/dev/null" 2> "/dev/null" & disown
    ;;
  esac
fi

info="$(
IFS="
"

for name in $ups_devices; do
  IFS="$IFS_"

  status="$(set +e; upsc "$name" "ups.status" 2> "/dev/null"; set -e)"
  charge="$(set +e; upsc "$name" "battery.charge" 2> "/dev/null"; set -e)"

  status_charge=""

  if [ "$charge" ]; then
    if [ "$charge" -gt "25" ]; then
      status_charge="${charge}%"
    else
      status_charge="⚠️ ${charge}%"
    fi
  fi

  case "$status" in
    "OL")
      echo "UPS${status_charge:+" ${status_charge}"}
UPS${status_charge:+" ${status_charge}"}"
    ;;
    "")
      echo "UPS disconnected
UPS discon."
    ;;
    *)
      echo "UPS: ${status}${status_charge:+", ${status_charge}"}
UPS ${status}${status_charge:+", ${status_charge}"}"
    ;;
  esac
done

IFS="$IFS_"
)"

cols="$(echo "$ups_devices" | wc -l)"

if [ "$info" ]; then
  echo "$info" | pr -"$cols" -t -s' '
fi
