#!/usr/bin/env sh
set -eu
LC_ALL="C"

STEP="${STEP:-"5"}"
BLOCK_BUTTON="${BLOCK_BUTTON:-""}"

[ "$BLOCK_BUTTON" ] && {
  case $BLOCK_BUTTON in
    1) easyeffects 1>/dev/null 2>/dev/null & disown ;;
    3) wpctl set-mute @DEFAULT_SINK@ toggle ;;
    4) wpctl set-mute @DEFAULT_SINK@ 0; wpctl set-volume @DEFAULT_SINK@ "${STEP}%+" ;;
    5) wpctl set-mute @DEFAULT_SINK@ 0; wpctl set-volume @DEFAULT_SINK@ "${STEP}%-" ;;
  esac
}

status="$(wpctl get-volume @DEFAULT_SINK@)"

[ "$status" ] && {
  volume="$(echo "$status" | cut -d' ' -f2)"
  muted="$(echo "$status" | cut -d' ' -f3)"
  volume_formatted="$(printf '%.0f%%' "$(echo "100 * ${volume}" | bc)")"
  echo "${PREFIX}${volume_formatted}${muted:+, MUTE}${SUFFIX}"
}
