include theme/vscode-dark.conf

font_family Cascadia Code PL
font_size 13.5
disable_ligatures always
adjust_line_height 129%
cursor_blink_interval 0
scrollback_lines 100000
window_padding_width 0
confirm_os_window_close 0
macos_option_as_alt yes
initial_window_width  120c
initial_window_height 30c
macos_titlebar_color background
macos_quit_when_last_window_closed yes
macos_colorspace displayp3
macos_show_window_title_in window

geninclude dynamic
