include theme/vscode-dark.conf

adjust_line_height 118%
box_drawing_scale 0.001, 0.5, 1.5, 2
confirm_os_window_close 0
cursor_blink_interval 0
cursor_beam_thickness 1
disable_ligatures always
font_family monospace
font_size 13.5
initial_window_height 30c
initial_window_width  120c
macos_colorspace displayp3
macos_option_as_alt yes
macos_quit_when_last_window_closed yes
macos_show_window_title_in window
macos_titlebar_color background
placement_strategy top-left
scrollback_lines 100000
text_composition_strategy legacy
window_padding_width 0

geninclude dynamic
