#!/usr/bin/env sh

# 'git' alias must precede the 'g*', 'g_*' aliases
# 'dotgit' alias must precede the 'dg*', 'dg_*' aliases
# 'htop' alias must precede the 't' alias
# 'yay' alias must precede the 'pac_*' aliases
alias \
  apack="apack --explain" \
  aunpack="aunpack --subdir --explain" \
  bc="bc -ql" \
  beeper_toggle="upscmd \"\$(upsc -L | head | cut -d\":\" -f1)\" \"beeper.toggle\"" \
  cl="clear" \
  cal="calcurse" \
  calc="qalc -c" \
  c="\$EDITOR \"\${XDG_CONFIG_HOME:-\$HOME/.config/}\"" \
  convert="magick" \
  cp="cp -rv" \
  curl="curl --location" \
  date_iso8601_utc="TZ=\"\" date -u +\"%Y-%m-%dT%H:%M:%SZ\"" \
  date_iso8601_utc_dash="TZ=\"\" date -u +\"%Y-%m-%dT%H-%M-%SZ\"" \
  date_iso8601_utc_nosep="TZ=\"\" date -u +\"%Y%m%dT%H%M%SZ\"" \
  date_iso8601_utc_underscore="TZ=\"\" date -u +\"%Y_%m_%dT%H_%M_%SZ\"" \
  dmesg="sudo dmesg -HL" \
  d="\$EDITOR \"\${XDG_DATA_HOME:-\$HOME/.local/share}\"" \
  diff="diff --color=always" \
  doc="\$EDITOR \"\${XDG_DATA_HOME:-\$HOME/.local/share}/doc/\"" \
  dotgit="dotgit -c color.ui=always" \
  dg="dotgit" \
  dg_submodule_init="dotgit submodule update --init --recursive" \
  dg_submodule_upgrade_latest_remote="dotgit submodule update --recursive --remote" \
  dgc="dotgit commit -a" \
  dgca="dotgit commit --amend" \
  dgcan="dotgit commit --amend --no-edit" \
  dgcm="dotgit commit -a -m" \
  dgd="dotgit diff" \
  dgl="dotgit log" \
  dgpl="dotgit pull" \
  dgps="dotgit push" \
  dgs="dotgit status" \
  dgt="dotgit checkout" \
  dup="rmlint" \
  e="\$EDITOR" \
  fd="fd --hidden" \
  g="git" \
  g_submodule_init="git submodule update --init --recursive" \
  g_submodule_upgrade_latest_remote="git submodule update --recursive --remote" \
  gc="git commit" \
  gca="git commit --amend" \
  gcan="git commit --amend --no-edit" \
  gcm="git commit -m" \
  gd="git diff" \
  gl="git log" \
  gpl="git pull" \
  gps="git push" \
  grep="grep --color=always" \
  gs="git status" \
  gt="git checkout" \
  hosts="sudo \$EDITOR /etc/hosts" \
  htop="htop -t -s PERCENT_CPU --highlight-changes=10" \
  inxi="inxi -c7 -F -xxx -y 120 --indent 15 --indents 4" \
  ip="ip --color=always" \
  jq="jq -C" \
  l="lf" \
  le="exec lf" \
  lfe="exec lf" \
  lsl="ls -l" \
  mime="file --mime-type --brief" \
  mkdir="mkdir -pv" \
  mount="sudo mount" \
  mv="mv -v" \
  myip="curl --silent \"https://ipinfo.io/\" | jq" \
  n="\$EDITOR \$HOME/note/" \
  ncdu="ncdu --color dark -x" \
  nethogs="sudo nethogs -l" \
  p="python3 -q" \
  pacman="yay --color=always" \
  yay="yay --color=always" \
  pac_ls_installed="yay -Q" \
  pac_ls_installed_explicit="yay -Qe" \
  pac_ls_installed_in_sync_db="yay -Qn" \
  pac_ls_installed_not_in_sync_db="yay -Qm" \
  pac_pkg_db_info="yay -Si" \
  pac_pkg_installed_info="yay -Qi" \
  pac_pkg_installed_info_files="yay -Qlk" \
  pac_search_db="yay -Ss" \
  pac_search_installed="yay -Qs" \
  pac_stats="yay -P --stats" \
  pac_upgrade="yay" \
  pac_upgrade_db="yay -Sy" \
  pkg="\$EDITOR \"\${XDG_DATA_HOME:-\$HOME/.local/share}/pkg_list/\"" \
  ports="sudo ss -tunlp" \
  py="python3 -q" \
  python3="python3 -q" \
  python="python3 -q" \
  :q="exit" \
  q="exit" \
  qq="exit" \
  qalc="qalc -c" \
  qr_txt="qrencode -t ansiutf8" \
  qr_receive="qrcp receive" \
  qr_send="qrcp send" \
  r="radian" \
  rm="rm -vI" \
  rsync_progress="rsync -r --progress --human-readable --stats" \
  s="\$EDITOR \$HOME/snippet/" \
  scan_http="sudo nmap -sS --open -p 80,447 192.168.1.0/24" \
  scan_smb="sudo nmap -sS --open -p 445 192.168.1.0/24" \
  scan_ssh="sudo nmap -sS --open -p 22 192.168.1.0/24" \
  sl="ls" \
  su="sudo su --login" \
  t="htop" \
  T="TMOUT=5400" \
  T0="TMOUT=0" \
  umount="sudo umount" \
  unlock_user="sudo faillock --reset --user" \
  tree="tree -CF" \
  viff="nvim -d" \
  wget="wget --hsts-file=\"\${XDG_DATA_HOME:-\$HOME/.local/share}/wget-hsts\""

alias_gnu_ls="ls -xhAFNX --color=always --group-directories-first --time-style=long-iso"

# shellcheck disable=SC3028
case "${OSTYPE:-"$(uname)"}" in
  [lL]"inux"*)
    # shellcheck disable=SC2139
    alias \
      ls="$alias_gnu_ls" \
      hexdump="hexdump --color=always --canonical"
  ;;
  *)
    alias hexdump="hexdump -C"

    if [ "$HAS_BREW_GNUBIN" ]; then
      # shellcheck disable=SC2139
      alias ls="$alias_gnu_ls"
    else
      alias ls="ls -xhAF --color=always"
    fi
  ;;
esac
