#!/usr/bin/env sh
# fn: detect if given command is executable
is_exec() { [ "$(command -v "$1")" ]; }

# 'git' alias must precede the 'g*', 'g_*' aliases
# 'dotgit' alias must precede the 'dg*', 'dg_*' aliases
alias \
  aunpack="aunpack --subdir --explain" \
  bc="bc -ql" \
  c="clear" \
  cal="calcurse" \
  calc="qalc -c" \
  convert="magick" \
  cp="cp -rv" \
  date_iso8601="date -u +\"%Y-%m-%dT%H:%M:%SZ\"" \
  dmesg="sudo dmesg -HL" \
  dotgit="dotgit -c color.ui=always" \
  dg="dotgit" \
  dg_submodule_init="dotgit submodule update --init --recursive" \
  dg_submodule_upgrade_latest_remote="dotgit submodule update --recursive --remote" \
  dgc="dotgit commit -a" \
  dgca="dotgit commit --amend" \
  dgcan="dotgit commit --amend --no-edit" \
  dgcm="dotgit commit -a -m" \
  dgd="dotgit diff" \
  dgl="dotgit log" \
  dgpl="dotgit pull" \
  dgps="dotgit push" \
  dgs="dotgit status" \
  dgt="dotgit checkout" \
  dirsize="du -sch *" \
  e="\$EDITOR" \
  fsize="du -ah" \
  git="git -c color.ui=always" \
  g="git" \
  g_submodule_init="git submodule update --init --recursive" \
  g_submodule_upgrade_latest_remote="git submodule update --recursive --remote" \
  gc="git commit" \
  gca="git commit --amend" \
  gcan="git commit --amend --no-edit" \
  gcm="git commit -m" \
  gd="git diff" \
  gl="git log" \
  gpl="git pull" \
  gps="git push" \
  gs="git status" \
  gt="git checkout" \
  h="tldr" \
  inxi="inxi -c7 -F" \
  ip="ip --color=auto" \
  mime="file --mime-type --brief" \
  mkdir="mkdir -pv" \
  mount="sudo mount" \
  mv="mv -v" \
  myip="curl https://ipinfo.io/" \
  n="\$EDITOR \$HOME/note/" \
  ncdu="ncdu -x" \
  p="python3 -q" \
  py="python3 -q" \
  python="python3 -q" \
  python3="python3 -q" \
  :q="exit" \
  q="exit" \
  qq="exit" \
  qalc="qalc -c" \
  qr_txt="qrencode -t ansiutf8" \
  qr_receive="qrcp receive" \
  qr_send="qrcp send" \
  r="radian" \
  rm="rm -vI" \
  rsync_progress="rsync --progress --human-readable --stats" \
  s="\$EDITOR \$HOME/snippet/" \
  scan_http="sudo nmap -sS --open -p 80,447 192.168.1.0/24" \
  scan_smb="sudo nmap -sS --open -p 445 192.168.1.0/24" \
  scan_ssh="sudo nmap -sS --open -p 22 192.168.1.0/24" \
  T="TMOUT=5400" \
  T0="TMOUT=0" \
  umount="sudo umount" \
  tree="tree -CF" \
  viff="nvim -d" \
  wget="wget --hsts-file=\"\${XDG_DATA_HOME:-\$HOME/.local/share}/wget-hsts\""

# 'yay' alias must precede the 'pac_*' aliases
is_exec "yay" && alias \
  pacman="yay --color=auto" \
  yay="yay --color=auto" \
  pac_ls_installed="yay -Q" \
  pac_ls_installed_explicit="yay -Qe" \
  pac_ls_installed_in_sync_db="yay -Qn" \
  pac_ls_installed_not_in_sync_db="yay -Qm" \
  pac_pkg_db_info="yay -Si" \
  pac_pkg_installed_info="yay -Qi" \
  pac_pkg_installed_info_files="yay -Qlk" \
  pac_search_db="yay -Ss" \
  pac_search_installed="yay -Qs" \
  pac_stats="yay -P --stats" \
  pac_upgrade="yay" \
  pac_upgrade_db="yay -Sy"

case "$(uname)" in
  "Darwin")
    is_macos="1"
  ;;
esac

if [ -z "$is_macos" ] || [ "${HAS_BREW_GNUBIN:-""}" ]; then
  alias \
    diff="diff --color=always" \
    grep="grep --color=always" \
    ls="ls -xhAFNX --color=always --group-directories-first --time-style=long-iso"
fi
