#!/usr/bin/env sh

# Xft/DPI in xrdb is the font resolution in DPI (dots/inch).
# The corresponding xsettingsd value is 1024*DPI.
#
#     % | DPI | 1024*DPI
# ------|-----|---------
# 100.0 |  96 |    98304
# 112.5 | 108 |   110592
# 125.0 | 120 |   122880
# 137.5 | 132 |   135168
# 150.0 | 144 |   147456
# 162.5 | 156 |   159744
# 175.0 | 168 |   172032
# 187.5 | 180 |   184320
# 200.0 | 192 |   196608

export GUI_FONT_FAMILY_TERM="mono"
export GUI_FONT_FAMILY_GUI="sans-serif"
export GUI_FONT_STYLE="medium"
export GUI_FONT_SIZE="13.5"
export GUI_FONT_SIZE_X11="12"
export GUI_FONT_SIZE_GTK="11"
export GUI_FONT_DPI="108"
export GUI_MENU_LINE_COUNT="25"

# vscode dark
export GUI_COLOR_FOREGROUND="#d4d4d4"
export GUI_COLOR_BACKGROUND="#1f1f1f"
export GUI_COLOR_ROOT_BACKGROUND="#2b2b2b"
export GUI_COLOR_CURSOR="#d4d4d4"
export GUI_COLOR_0="#1f1f1f"
export GUI_COLOR_1="#f44747"
export GUI_COLOR_2="#608b4e"
export GUI_COLOR_3="#dcdcaa"
export GUI_COLOR_4="#569cd6"
export GUI_COLOR_5="#c678dd"
export GUI_COLOR_6="#56b6c2"
export GUI_COLOR_7="#d4d4d4"
export GUI_COLOR_8="#808080"
export GUI_COLOR_9="#f44747"
export GUI_COLOR_A="#608b4e"
export GUI_COLOR_B="#dcdcaa"
export GUI_COLOR_C="#569cd6"
export GUI_COLOR_D="#c678dd"
export GUI_COLOR_E="#56b6c2"
export GUI_COLOR_F="#d4d4d4"

# # vscode light
# export GUI_COLOR_FOREGROUND="#000000"
# export GUI_COLOR_BACKGROUND="#ffffff"
# export GUI_COLOR_ROOT_BACKGROUND="#d4d4d4"
# export GUI_COLOR_CURSOR="#000000"
# export GUI_COLOR_0="#ffffff"
# export GUI_COLOR_1="#c72e0f"
# export GUI_COLOR_2="#008000"
# export GUI_COLOR_3="#795e25"
# export GUI_COLOR_4="#007acc"
# export GUI_COLOR_5="#af00db"
# export GUI_COLOR_6="#56b6c2"
# export GUI_COLOR_7="#000000"
# export GUI_COLOR_8="#808080"
# export GUI_COLOR_9="#c72e0f"
# export GUI_COLOR_A="#008000"
# export GUI_COLOR_B="#795e25"
# export GUI_COLOR_C="#007acc"
# export GUI_COLOR_D="#af00db"
# export GUI_COLOR_E="#56b6c2"
# export GUI_COLOR_F="#000000"
