#!/usr/bin/env sh

# configure windows terminal
# if [ "$WT_SESSION" ]; then
#   export COLORTERM="truecolor"
# fi

# launch tmux
if [ -z "${TMUX:-""}" ] && [ "$TERM" != "linux" ] && [ -z "${NO_TMUX:-""}" ]; then
  # shellcheck disable=SC3028
  case "${OSTYPE:-"$(uname)"}" in
    [Dd]"arwin"*)
      if [ "${UID:-"$(id -u)"}" -ge "501" ] && command -v "tmux" 1>/dev/null 2>/dev/null; then
        exec tmux
      fi
    ;;
    *)
      if [ "${UID:-"$(id -u)"}" -ge "1000" ] && command -v "tmux" 1>/dev/null 2>/dev/null; then
        exec tmux
      fi
    ;;
  esac
fi

# set window title
printf "\033]0;%s\007" "$PWD"

# disable ctrl-s to freeze terminal
stty "stop" "undef"

# inactivity timeout
TMOUT="5400"

# storing history in memory
HISTSIZE="1000000"

# configure gpg
export GPG_TTY="${TTY:-"$(tty)"}"

# alias
# shellcheck disable=SC1091
. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/alias"

# configure X11
# shellcheck disable=SC3028
if [ "${DISPLAY:-""}" ] && [ "${UID:-"$(id -u)"}" -lt "1000" ]; then
  unset DISPLAY
fi

if [ -z "${HAS_INTERACTIVE_SET:-""}" ]; then
  # history file path
  export HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/shell/history"

  export PATH="${XDG_DATA_HOME:-$HOME/.local/share}/pyenv/shims:${PATH}"

  export HAS_INTERACTIVE_SET="1"
fi

# lfcd
lfcd() { cd "$(command lf -print-last-dir "$@")" || return; }

# configure pyenv
# if command -v "pyenv" 1>/dev/null 2>/dev/null; then
#   eval "$(pyenv init - zsh)"
# fi

pyenv() {
  command="${1:-""}"

  if [ "$#" -gt "0" ]; then
    shift
  fi

  case "$command" in
    "rehash"|"shell")
      eval "$(pyenv "sh-$command" "$@")"
    ;;
    *)
      command pyenv "$command" "$@"
    ;;
  esac
}
