#!/usr/bin/env sh

# Preventing running this script with a system account (e.g. root)

if [ "$(id -u)" -lt 1000 ]; then
  echo "$(basename "$0"): Must not use a system account" 2>&1
  exit 1
fi

# gsettings

"${XDG_CONFIG_HOME:-$HOME/.config}/gsettings/init"

# .Xresources

## xrdb

xrdb -load "${XDG_CONFIG_HOME:-$HOME/.config}/xresources/.Xresources"

pathf_xresources_local="${XDG_CONFIG_HOME:-$HOME/.config}/xresources/local.Xresources"
[ -f "$pathf_xresources_local" ] && xrdb -override "$pathf_xresources_local"

## xsettingsd

"${XDG_DATA_HOME:-$HOME/.local/share}/xsettingsd/init" &

# Starting VirtualBox guest service

VBoxClient-all &

# Disabling the console bell beep in X11

xset b off &

# Adjusting keyboard key repetition rate in X11

xset r rate 165 55 &

# Loading the X11 keyboard layout

xkbcomp -w 4 -I"${XDG_CONFIG_HOME:-$HOME/.config}/xkb" "${XDG_CONFIG_HOME:-$HOME/.config}/xkb/keymap/kbd" "$DISPLAY" &

# Running unclutter to automatically hide the mouse pointer
[ -z "$(pidof unclutter)" ] && unclutter --timeout 1 --start-hidden &

# Setting the X11 root window background

hsetroot -solid "$(xrdb -get background)" &

# Starting or reloading X11 display compositor

pid_picom="$(pidof picom)"
if [ "$pid_picom" ]; then 
  kill -USR1 "$pid_picom" &
else 
  picom -b --config "/dev/null" &
fi

# xscreensaver

## Starting or reloading xscreensaver

if [ "$(pidof xscreensaver)" ]; then 
  xscreensaver-command --restart &
else
  xscreensaver --no-splash & 
fi

## Starting xss-lock

[ -z "$(pidof xss-lock)" ] && xss-lock --ignore-sleep -- xscreensaver-command -lock &

# Running EeasyEffects audio effects interface

[ -z "$(pidof easyeffects)" ] && easyeffects --gapplication-service &

# Starting or reloading i3 window manager

if [ "$(pidof i3)" ]; then 
  i3-msg restart
else
  exec i3
fi
