#!/usr/bin/env sh

# Preventing running this script with a system account (e.g. root)

if [ "$(id -u)" -lt 1000 ]; then
  echo "$(basename "$0"): Must not use a system account" 2>&1
  exit 1
fi

# gsettings

"${XDG_CONFIG_HOME:-$HOME/.config}/gsettings/init"

# .Xresources

## xrdb

xrdb -load "${XDG_CONFIG_HOME:-$HOME/.config}/xresources/.Xresources"

pathf_xresources_local="${XDG_CONFIG_HOME:-$HOME/.config}/xresources/local.Xresources"

if [ -f "$pathf_xresources_local" ]; then
  xrdb -override "$pathf_xresources_local"
fi

## xsettingsd

"${XDG_DATA_HOME:-$HOME/.local/share}/xsettingsd/init" &

# Starting VirtualBox guest service

VBoxClient-all &

# Notification-daemon
if ! pidof -q "dunst"; then
  dunst &
fi

# Polkit authentication agent

if ! pidof -q "polkit-gnome-authentication-agent-1"; then
  /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Disabling the console bell beep in X11

xset b off &

# Adjusting keyboard key repetition rate in X11

xset r rate 165 55 &

# Loading the X11 keyboard layout

xkbcomp -w 4 -I"${XDG_CONFIG_HOME:-$HOME/.config}/xkb" "${XDG_CONFIG_HOME:-$HOME/.config}/xkb/keymap/kbd" "$DISPLAY" &

# Running unclutter to automatically hide the mouse pointer

if ! pidof -q "unclutter"; then
  unclutter --timeout 1 --start-hidden &
fi

# Setting the X11 root window background

hsetroot -solid "$(xrdb -get "rootBackground")" &

# Starting or reloading X11 display compositor

pid_picom="$(pidof "picom")"
if [ "$pid_picom" ]; then
  kill -USR1 "$pid_picom" &
else
  picom -b --config "/dev/null" &
fi

# xscreensaver, xss-lock

idle_manager "start" &

# EeasyEffects audio effects interface

if ! pidof -q "easyeffects"; then
  easyeffects --gapplication-service &
fi

# Starting or reloading i3 window manager

if ! pidof -q "i3"; then 
  i3-msg "restart"
else
  exec i3
fi
