#!/usr/bin/env sh

# GUI environment variables

. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/gui.sh"

# gsettings

schema="org.gnome.desktop.interface"

gsettings "set" "$schema" "cursor-size" "$GUI_CURSOR_SIZE"
gsettings "set" "$schema" "text-scaling-factor" "1.15"
gsettings "set" "$schema" "color-scheme" "prefer-dark"
gsettings "set" "$schema" "enable-animations" "false"
gsettings "set" "$schema" "cursor-blink" "false"
gsettings "set" "$schema" "font-name" "${GUI_FONT_FAMILY_GUI} ${GUI_FONT_STYLE_GUI} 11"
