#!/usr/bin/env sh
set -eu

. "$GUI_ENV"

s="gsettings set"

$s "org.gnome.desktop.interface"  "color-scheme"              "prefer-dark"
$s "org.gnome.desktop.interface"  "cursor-blink"              "false"
$s "org.gnome.desktop.interface"  "cursor-size"               "42"
$s "org.gnome.desktop.interface"  "enable-animations"         "false"
$s "org.gnome.desktop.interface"  "font-name"                 "${GUI_FONT_FAMILY_GUI} ${GUI_FONT_STYLE} ${GUI_FONT_SIZE_GTK}"
$s "org.gnome.desktop.interface"  "monospace-font-name"       "${GUI_FONT_FAMILY_TERM} ${GUI_FONT_SIZE_GTK}"
$s "org.gnome.desktop.interface"  "text-scaling-factor"       "1.15"
$s "org.gnome.desktop.privacy"    "recent-files-max-age"      "-1"
$s "org.gnome.desktop.privacy"    "remember-recent-files"     "false"
$s "org.gnome.desktop.privacy"    "report-technical-problems" "false"
$s "org.gnome.desktop.privacy"    "send-software-usage-stats" "false"
$s "org.gtk.Settings.FileChooser" "date-format"               "with-time"
$s "org.gtk.Settings.FileChooser" "show-hidden"               "true"
$s "org.gtk.Settings.FileChooser" "sort-directories-first"    "true"
