#!/usr/bin/env sh

[ "$(pidof "swayidle")" ] && killall -u "$(whoami)" "swayidle"

exec swayidle -w \
  timeout "100" "swaymsg 'output * dpms off'" \
    resume "swaymsg 'output * dpms on'" \
  timeout "120" "swaylock -u -f -c 000000" \
    resume "swaymsg 'output * dpms on'" \
  before-sleep "swaylock -u -f -c 000000"
