#!/usr/bin/env sh

killall -u "$(whoami)" "swayidle"
exec swayidle -w \
  timeout "60" "swaylock -u -f -c 000000" \
  timeout "90" "swaymsg \"output * dpms off\"" \
  resume "swaymsg \"output * dpms on\" && sway-audio-idle-inhibit &" \
  before-sleep "swaylock -u -f -c 000000"
