#!/usr/bin/env sh
set -eu

pid="$(swaymsg -t get_tree | jq '.. | select(.type?)| select(.focused == true).pid')"

if [ -z "$pid" ]; then
  exit "1"
fi

swaynag -t "warning" -m "Kill process PID ${pid}?" -Z "Yes" "kill -9 ${pid}"
