#!/usr/bin/env sh
set -eu

tmp="$(mktemp --suffix="_tmux_pane_copy")"

[ "$tmp" ] || exit "1"

echo "# vi: nowrap ft=
$(tmux capture-pane -pS -)" > "$tmp"

arg=""
case "$EDITOR" in
  "vi"|"vim"|"nvim"|"nano") arg="\+$(wc -l "$tmp")" ;;
esac

tmux split-pane "cat ${tmp} | ${EDITOR} ${arg}; rm ${tmp}"
