#!/usr/bin/env sh
set -eu

tmp="$(mktemp --suffix="_tmux_pane_copy")"

[ -z "$tmp" ] && exit 1

echo "# vi: nowrap ft=$(tmux capture-pane -pS -)" > "$tmp"

arg=""
case "$EDITOR" in
  "nvim"|"vim") arg="\+$(wc -l "$tmp")" ;;
esac

tmux split-pane "cat ${tmp} | ${EDITOR} ${arg}; rm ${tmp}"
