#!/usr/bin/env sh
set -eu

case "$(tmux show-options -g status)" in
  "status off")
    tmux set-option -g status on

    (
      id_file_dir="${XDG_CACHE_HOME:-$HOME/.cache}/tmux"
      id_file_fpath="${id_file_dir}/status_autohide_id"

      mkdir -p "$id_file_dir"

      id="$(od -vAn -N2 -tu2 < /dev/urandom | tr -d ' ')"

      echo "$id" > "$id_file_fpath"

      sleep 5; 

      [ -f "$id_file_fpath" ] && [ "$id" = "$(cat "$id_file_fpath")" ] && {
        rm "$id_file_fpath"
        tmux set-option -g status off
      }
    ) 1>/dev/null 2>/dev/null & disown
  ;;
  "status on")
    tmux set-option -g status off
  ;;
  *)
    exit 1
  ;;
esac
