#!/usr/bin/env sh

[ "$1" ] || exit "2"

case "$1" in
  "f")
    while read file; do file_manager_desktop "$file" & done
  ;;
  "Y")
    files="$(while read file; do echo "${files:+
}$file"; done)"

    [ "$WAYLAND_DISPLAY" ] && [ "$(command -v "wl-copy")" ] && {
      printf '%s' "$files" | wl-copy
      exit
    }

    [ "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && [ "$(command -v "xclip")" ] && {
      printf '%s' "$files" | xclip -sel "clipboard"
      exit
    }

    exit "1"
  ;;
  "y")
    [ "$WAYLAND_DISPLAY" ] && [ "$(command -v "wl-copy")" ] && {
      while read file; do "wl-copy" < "$file" ; done
      exit
    }

    [ "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && [ "$(command -v "xclip")" ] && {
      while read file; do xclip -selection "clipboard" -target "image/png" "$file"; done
      exit
    }

    exit "1"
  ;;
  "o")
    files="$(while read file; do echo "${files:+
}$file"; done)"
    openwith_menu_desktop "$files"
  ;;
  "h")
    $TERMINAL -e "$SHELL" -c "$PAGER ${XDG_CONFIG_HOME:-$HOME/.config}/nsxiv/exec/key-handler" 1> "/dev/null" 2> "/dev/null" & disown
  ;;
  *)
    exit "2";
  ;;
esac
