#!/usr/bin/env bash

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# generic interactive shell configuration
. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/interactive"

PS1='[\u@\h \W]\$ '

# history file length in lines
export HISTFILESIZE="500"

# configure pyenv

# if is_exec "pyenv"; then
#   eval "$(pyenv init - bash)"
# fi

export PYENV_SHELL="bash"
