#!/usr/bin/env bash

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# generic interactive shell configuration
. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/interactive"

PS1='[\u@\h \W]\$ '

# storing history in history file
HISTFILESIZE="500"
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/bash/history"
