#!/usr/bin/env bash

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# generic interactive shell configuration
. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/interactive"

PS1='[\u@\h \W]\$ '
