#!/usr/bin/env sh

# generic login shell configuration
. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/login"

# fn: detect if given command is executable
is_exec() {
  command -v "$1" 1>/dev/null 2>/dev/null
}

# configure pyenv

# if is_exec "pyenv"; then
#   eval "$(pyenv init - bash)"
# fi

export PATH="${XDG_DATA_HOME:-$HOME/.local/share}/pyenv/shims:${PATH}"
export PYENV_SHELL="bash"

pyenv() {
  command="${1:-""}"

  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
    "rehash"|"shell")
      eval "$(pyenv "sh-$command" "$@")"
    ;;
    *)
      command pyenv "$command" "$@"
    ;;
  esac

  unset command
}
