#!/bin/bash
#TODO: multimonitor support
i3-msg floating enable >/dev/null 2>&1 &
xdotool $(echo $(xdotool getdisplaygeometry getwindowfocus) | awk 'BEGIN{FS=" "}{printf "%s %s %.0f %.0f %s %s %.0f %.0f","windowmove",$3,$1*0.45,$2*0.45,"windowsize",$3,$1-($1*0.45)-6,$2-($2*0.45)-6}') >/dev/null 2>&1 &
