#!/usr/bin/env sh

argsFile=$(mktemp)

for match in "$@"; do
  printf %q"\n" "$(readlink -f "$match")" >> $argsFile
done

$EDITOR $argsFile
readarray -t arrArgs < $argsFile
rm $argsFile

for item in "${arrArgs[@]}"; do
  echo "--------------------------------------------------
Unpacking $item
--------------------------------------------------"
  aunpack -D "$(echo $item | sed 's/[\]//g')"
done
