#!/bin/bash

argsFile=/tmp/unpack-$(date +%s3N).txt

for match in "$@"
do
    printf %q"\n" "$(readlink -f "$match")" >> $argsFile
done

$EDITOR $argsFile

readarray -t arrArgs < $argsFile

rm $argsFile

for item in "${arrArgs[@]}"
do
    echo "--------------------------------------------------"
    echo "Unpacking $item"
    echo "--------------------------------------------------"
    aunpack -D "$(echo $item | sed 's/[\]//g')"
done
