#!/usr/bin/env sh
set -eu

wm="${WAYLAND_DISPLAY:+"sway"}"
wm="${wm:-"i3"}"

if ! pidof -q "$wm"; then
  exit
fi

file_pid="/tmp/${USER}_${wm}_auto_edge_snap_pid"
pid="$(set +e; cat "$file_pid" 2> "/dev/null"; set -e)"

if [ "$pid" ] && kill -0 "$pid" 2> "/dev/null"; then
  exit
fi

echo "$$" > "$file_pid"

IN()  { test "$((($3 - $1 - 1) * ($2 - $3)))" -gt "0"; } # $3 -ge $1 && $3 -lt $2
OUT() { test "$((($3 - $1 - 1) * ($2 - $3)))" -le "0"; } # $3 -ge $1 && $3 -lt $2

ABN() {
  AS="$1" BS="$2" AZ="$3" BZ="$4" AI="$5" BI="$6" AO="$7" BO="$8"

  A="$AZ" B="$((AS + BZ - BS))" N="$AS"

  if [ "$AZ" -eq "$AS" ] || [ "$BZ" -eq "$BS" ]; then echo "$N"; return; fi

  if IN "$AI" "$BI" "$AS"; then
    if IN "$AI" "$BI" "$BS" || OUT "$AO" "$BO" "$BS"; then echo "$N"; return; fi
    if IN "$BI" "$BZ" "$BS" || IN "$BZ" "$BO" "$BS"; then echo "$B"; return; fi
  fi

  if IN "$AZ" "$AI" "$AS" || IN "$AO" "$AZ" "$AS"; then
    if IN "$AI" "$BI" "$BS" || OUT "$AO" "$BO" "$BS" || IN "$AZ" "$AI" "$BS" || (IN "$AO" "$AZ" "$AS" && IN "$AO" "$AZ" "$BS"); then echo "$A"; return; fi

    if IN "$BI" "$BZ" "$BS"; then
      if [ "$((AS - AZ))" -le "$((BZ - BS))" ]; then echo "$A"; return; else echo "$B"; return; fi
    fi

    if IN "$BZ" "$BO" "$BS"; then
      if [ "$((AS - AZ))" -le "$((BS - BZ))" ]; then echo "$A"; return; else echo "$B"; return; fi
    fi
  fi

  if OUT "$AO" "$BO" "$AS" || IN "$BI" "$BZ" "$AS" || IN "$BZ" "$BO" "$AS"; then
    if IN "$BZ" "$BO" "$BS" || IN "$BI" "$BZ" "$BS"; then echo "$B"; return; fi

    if OUT "$AO" "$BO" "$AS"; then
      if IN "$AI" "$BI" "$BS" || IN "$AZ" "$AI" "$BS" || IN "$AO" "$AZ" "$BS" || OUT "$AO" "$BO" "$BS"; then echo "$N"; return; fi
    fi
  fi

  if OUT "$AO" "$BO" "$BS"; then
    if IN "$BI" "$BZ" "$AS" || IN "$BZ" "$BO" "$AS" || OUT "$AO" "$BO" "$AS"; then echo "$N"; return; fi
  fi
}

case "$wm" in
  "sway")
    wm_cmd="swaymsg"
    win_edge_top_jq=".rect.y - .deco_rect.height"
    win_height_jq=".rect.height + .deco_rect.height"
  ;;
  "i3")
    wm_cmd="i3-msg"
    win_edge_top_jq=".rect.y"
    win_height_jq=".rect.height"
  ;;
esac

ws_thr_jq='((.rect.width + .rect.height) / 40 | floor)'

data_jq="
.[] | select(.focused) |
  if .floating_nodes | .[] | select(.focused) then
    (.floating_nodes | .[] | select(.focused) | .rect.x, .rect.x + .rect.width),
    .rect.x, .rect.x + .rect.width, .rect.x + ${ws_thr_jq}, .rect.x + .rect.width - ${ws_thr_jq}, .rect.x - ${ws_thr_jq}, .rect.x + .rect.width + ${ws_thr_jq},
    (.floating_nodes | .[] | select(.focused) | ${win_edge_top_jq}, ${win_edge_top_jq} + ${win_height_jq}),
    .rect.y, .rect.y + .rect.height, .rect.y + ${ws_thr_jq}, .rect.y + .rect.height - ${ws_thr_jq}, .rect.y - ${ws_thr_jq}, .rect.y + .rect.height + ${ws_thr_jq}
  end
"

while true; do
  data="$($wm_cmd -r -t "get_workspaces" | jq -r "$data_jq")"

  if [ "$data" ]; then
    set +e # The focused window may not be floating anymore
    # shellcheck disable=SC2046
    $wm_cmd -q "move absolute position $(ABN $(echo "$data" | head -8)) $(ABN $(echo "$data" | tail -8))"
    set -e
  fi

  sleep "1"
done
