#!/usr/bin/env sh
set -eu
NL="
"

wm="${WAYLAND_DISPLAY:+"sway"}"
wm="${wm:-"i3"}"

if ! pidof -q "$wm"; then
  exit
fi

file_pid="/tmp/${USER}_${wm}_auto_edge_snap_pid"
pid="$(set +e; cat "$file_pid" 2> "/dev/null"; set -e)"

if [ "$pid" ] && kill -0 "$pid" 2> "/dev/null"; then
  exit
fi

echo "$$" > "$file_pid"

case "$wm" in
  "sway")
    wm_cmd="swaymsg"
    win_edge_top_jq=".rect.y-.deco_rect.height"
    win_height_jq=".rect.height+.deco_rect.height"
  ;;
  "i3")
    wm_cmd="i3-msg"
    win_edge_top_jq=".rect.y"
    win_height_jq=".rect.height"
  ;;
esac

ws_thr_jq='((.rect.width+.rect.height)/40|floor)'

metrics_jq=".[]|select(.focused)|
if.floating_nodes|.[]|select(.focused)then
[(.floating_nodes|.[]|select(.focused)|.rect.x,.rect.x+.rect.width),
.rect.x,.rect.x+.rect.width,.rect.x+${ws_thr_jq},.rect.x+.rect.width-${ws_thr_jq},.rect.x-${ws_thr_jq},.rect.x+.rect.width+${ws_thr_jq},
(.floating_nodes|.[]|select(.focused)|${win_edge_top_jq},${win_edge_top_jq}+${win_height_jq}),
.rect.y,.rect.y+.rect.height,.rect.y+${ws_thr_jq},.rect.y+.rect.height-${ws_thr_jq},.rect.y-${ws_thr_jq},.rect.y+.rect.height+${ws_thr_jq}]|@sh
end"

IN() { return "$((($3 - $1) * ($2 - $3) > 0 ? 0 : 1))"; }

metrics_cache=""
prev_workspaces=""

while true; do
  workspaces="$($wm_cmd -r -t "get_workspaces")"

  if [ "$workspaces" = "$prev_workspaces" ]; then
    sleep "1"
    continue
  fi

  prev_workspaces="$workspaces"
  metrics="$(echo "$workspaces" | jq -r "$metrics_jq")"

  if [ -z "$metrics" ]; then
    sleep "1"
    continue
  fi

  set +e
  cache_hit="$(echo "$metrics_cache" | grep "^${metrics} ")"
  set -e

  if [ "$cache_hit" ]; then
    set +e # The focused window may not be floating anymore
    $wm_cmd -q "move absolute position $(echo "$cache_hit" | head -n 1 | cut -f17-18 -d" ")"
    set -e

    sleep "1"
    continue
  fi

  # shellcheck disable=SC2086
  set -- $metrics

  for axis in "X" "Y"; do
    case "$axis" in
      "X")
        AS="$1" BS="$2" AZ="$3" BZ="$4" AI="$5" BI="$6" AO="$7" BO="$8"
      ;;
      "Y")
        AS="$9" BS="${10}" AZ="${11}" BZ="${12}" AI="${13}" BI="${14}" AO="${15}" BO="${16}"
      ;;
    esac

    if [ "$(((AZ - AS) * (BZ - BS)))" -eq "0" ]; then set -- "$@" "$AS"; continue; fi

    if IN "$AO" "$AZ" "$AS" && IN "$AO" "$AZ" "$BS"; then set -- "$@" "$AZ"; continue; fi

    if IN "$AO" "$AI" "$AS"; then
      if IN "$AZ" "$BI" "$BS" || IN "$BO" "10000000" "$BS"; then set -- "$@" "$AZ"; continue; fi
      if IN "$BI" "$BO" "$BS"; then set -- "$@" "$(((AS - AZ > 0 ? AS - AZ : AZ - AS) <= (BS - BZ > 0 ? BS - BZ : BZ - BS) ? AZ : AS + BZ - BS))"; continue; fi
    fi

    if (! IN "$AO" "$AI" "$AS" || IN "$AI" "$BI" "$AS") && IN "$BI" "$BO" "$BS"; then set -- "$@" "$((AS + BZ - BS))"; continue; fi

    if IN "$AI" "$BI" "$AS" && ! IN "$AO" "$AI" "$BS" && ! IN "$BI" "$BO" "$BS"; then set -- "$@" "$AS"; continue; fi
    if ! IN "$AO" "$BO" "$AS" && ! IN "$BI" "$BO" "$BS"; then set -- "$@" "$AS"; continue; fi
    if IN "$BI" "$BO" "$AS" && ! IN "$AO" "$BO" "$BS"; then set -- "$@" "$AS"; continue; fi

    echo "Failure on: ${metrics}" >> "${XDG_CACHE_HOME:-$HOME/.cache}/auto_edge_snap.log"
    exit "2"
  done

  set +e # The focused window may not be floating anymore
  $wm_cmd -q "move absolute position ${17} ${18}"
  set -e

  metrics_cache="${*}${NL}$(echo "$metrics_cache" | head -50)"

  sleep "1"
done
