#!/usr/bin/env sh
set -eu

wm="${WAYLAND_DISPLAY:+"sway"}"
wm="${wm:-"i3"}"

if ! pidof -q "$wm"; then
  exit
fi

file_pid="/tmp/${USER}_${wm}_auto_edge_snap_pid"
pid="$(set +e; cat "$file_pid" 2> "/dev/null"; set -e)"

if [ "$pid" ] && kill -0 "$pid" 2> "/dev/null"; then
  exit
else
  echo "$$" > "$file_pid"
fi

AS_on_AZ()  { [ "$AS" -eq "$AZ" ]; }
BS_on_BZ()  { [ "$BS" -eq "$BZ" ]; }
AS_in_AI()  { [ "$AS" -ge "$AZ" ] && [ "$AS" -lt "$AI" ]; }
AS_in_AO()  { [ "$AS" -ge "$AO" ] && [ "$AS" -lt "$AZ" ]; }
AS_in_BI()  { [ "$AS" -ge "$BI" ] && [ "$AS" -lt "$BZ" ]; }
AS_in_BO()  { [ "$AS" -ge "$BZ" ] && [ "$AS" -lt "$BO" ]; }
AS_in_S()   { [ "$AS" -ge "$AI" ] && [ "$AS" -lt "$BI" ]; }
AS_out_AO() { [ "$AS" -lt "$AO" ]; }
AS_out_BO() { [ "$AS" -ge "$BO" ]; }
BS_in_AI()  { [ "$BS" -ge "$AZ" ] && [ "$BS" -lt "$AI" ]; }
BS_in_AO()  { [ "$BS" -ge "$AO" ] && [ "$BS" -lt "$AZ" ]; }
BS_in_BI()  { [ "$BS" -lt "$BZ" ] && [ "$BS" -ge "$BI" ]; }
BS_in_BO()  { [ "$BS" -lt "$BO" ] && [ "$BS" -ge "$BZ" ]; }
BS_in_S()   { [ "$BS" -ge "$AI" ] && [ "$BS" -lt "$BI" ]; }
BS_out_AO() { [ "$BS" -lt "$AO" ]; }
BS_out_BO() { [ "$BS" -ge "$BO" ]; }

A() { echo "$AZ"; }
B() { echo "$((AS + BZ - BS))"; }
N() { echo "$AS"; }

ABN() {
  AS="$1" BS="$2" AZ="$3" BZ="$4" AI="$5" BI="$6" AO="$7" BO="$8"

  if AS_on_AZ || BS_on_BZ; then N; return; fi

  if AS_in_S; then
    if BS_in_S || BS_out_BO; then N; return; fi
    if BS_in_BI || BS_in_BO; then B; return; fi
  fi

  if AS_in_AI || AS_in_AO; then
    if BS_in_S || BS_out_BO || BS_in_AI || (AS_in_AO && BS_in_AO); then A; return; fi

    if BS_in_BI; then
      if [ "$((AS - AZ))" -le "$((BZ - BS))" ]; then A; return; else B; return; fi
    fi

    if BS_in_BO; then
      if [ "$((AS - AZ))" -le "$((BS - BZ))" ]; then A; return; else B; return; fi
    fi
  fi

  if AS_out_AO || AS_in_BI || AS_in_BO; then
    if BS_in_BO || BS_in_BI; then B; return; fi

    if AS_out_AO; then
      if BS_in_S || BS_in_AI || BS_in_AO || BS_out_AO || BS_out_BO; then N; return; fi
    fi
  fi

  if BS_out_BO; then
    if AS_in_BI || AS_in_BO || AS_out_BO; then N; return; fi
  fi
}

case "$wm" in
  "sway")
    wm_cmd="swaymsg"
    win_edge_top_jq=".rect.y - .deco_rect.height"
    win_height_jq=".rect.height + .deco_rect.height"
  ;;
  "i3")
    wm_cmd="i3-msg"
    win_edge_top_jq=".rect.y"
    win_height_jq=".rect.height"
  ;;
esac

ws_thr_jq='((.rect.width + .rect.height) / 40 | floor)'

data_jq="
.[] | select(.focused) |
  if .floating_nodes | .[] | select(.focused) then
    (.floating_nodes | .[] | select(.focused) | .rect.x, .rect.x + .rect.width),
    .rect.x, .rect.x + .rect.width, .rect.x + ${ws_thr_jq}, .rect.x + .rect.width - ${ws_thr_jq}, .rect.x - ${ws_thr_jq}, .rect.x + .rect.width + ${ws_thr_jq},
    (.floating_nodes | .[] | select(.focused) | ${win_edge_top_jq}, ${win_edge_top_jq} + ${win_height_jq}),
    .rect.y, .rect.y + .rect.height, .rect.y + ${ws_thr_jq}, .rect.y + .rect.height - ${ws_thr_jq}, .rect.y - ${ws_thr_jq}, .rect.y + .rect.height + ${ws_thr_jq}
  end
"

while true; do
  data=$(swaymsg -r -t "get_workspaces" | jq -r "$data_jq")

  if [ "$data" ]; then
    # shellcheck disable=SC2046
    $wm_cmd -q "move absolute position $(ABN $(echo "$data" | sed "1,8!d")) $(ABN $(echo "$data" | sed "9,16!d"))"
  fi

  sleep "1"
done
