#!/usr/bin/env sh
set -eu

direction="${1:-""}"

if [ -z "$direction" ]; then
  exit "1"
fi

# Window manaager data

out_rect="$(i3-msg -t get_outputs | jq ".[] | select(.focused == true).rect")"

out_rect_x="$(echo "$out_rect" | jq -r ".x")"
out_rect_y="$(echo "$out_rect" | jq -r ".y")"
out_rect_width="$(echo "$out_rect" | jq -r ".width")"
out_rect_height="$(echo "$out_rect" | jq -r ".height")"

ws_rect="$(i3-msg -t get_workspaces | jq ".[] | select(.focused == true).rect")"

ws_rect_x="$(echo "$ws_rect" | jq -r ".x")"
ws_rect_y="$(echo "$ws_rect" | jq -r ".y")"
ws_rect_width="$(echo "$ws_rect" | jq -r ".width")"
ws_rect_height="$(echo "$ws_rect" | jq -r ".height")"

win="$(swaymsg -t get_tree | jq -r '.. | select(.type?) | select(.focused == true)')"
win_type="$(echo "$win" | jq -r ".type")"
win_rect="$(echo "$win" | jq -r '.rect')"
# win_window_rect="$(echo "$win" | jq -r '.window_rect')"
win_deco_rect="$(echo "$win" | jq -r '.deco_rect')"
# win_geometry="$(echo "$win" | jq -r '.geometry')"

win_rect_x="$(echo "$win_rect" | jq -r '.x')"
win_rect_y="$(echo "$win_rect" | jq -r '.y')"
win_rect_width="$(echo "$win_rect" | jq -r '.width')"
win_rect_height="$(echo "$win_rect" | jq -r '.height')"

# win_deco_rect_x="$(echo "$win_deco_rect" | jq -r '.x')"
# win_deco_rect_y="$(echo "$win_deco_rect" | jq -r '.y')"
# win_deco_rect_width="$(echo "$win_deco_rect" | jq -r '.width')"
win_deco_rect_height="$(echo "$win_deco_rect" | jq -r '.height')"

# Window properties

win_height() {
  echo $((win_rect_height + win_deco_rect_height))
}

win_width() {
  echo "$win_rect_width"
}

win_edge_left() {
  echo "$win_rect_x"
}

win_edge_right() {
  echo $(($(win_edge_left) + $(win_width)))
}

win_edge_top() {
  echo "$((win_rect_y - win_deco_rect_height))"
}

win_edge_bottom() {
  echo "$(($(win_edge_top) + $(win_height)))"
}

# Output properties

out_height() {
  echo "$out_rect_height"
}

out_width() {
  echo "$out_rect_width"
}

out_edge_left() {
  echo "$out_rect_x"
}

out_edge_right() {
  echo $(($(out_edge_left) + $(out_width)))
}

out_edge_top() {
  echo "$out_rect_y"
}

out_edge_bottom() {
  echo $(($(out_edge_top) + $(out_height)))
}

# Workspace properties

ws_height() {
  echo "$ws_rect_height"
}

ws_width() {
  echo "$ws_rect_width"
}

ws_edge_left() {
  echo "$ws_rect_x"
}

ws_edge_right() {
  echo $(($(ws_edge_left) + $(ws_width)))
}

ws_edge_top() {
  echo "$ws_rect_y"
}

ws_edge_bottom() {
  echo $(($(ws_edge_top) + $(ws_height)))
}

# Workspace-Window relation properties

win_edge_top_dist_ws_edge_top() {
  echo "$(($(win_edge_top) - $(ws_edge_top)))"
}

win_edge_bottom_dist_ws_edge_bottom() {
  echo "$(($(ws_edge_bottom) - $(win_edge_bottom)))"
}

win_edge_left_dist_ws_edge_left() {
  echo "$(($(win_edge_left) - $(ws_edge_left)))"
}

win_edge_right_dist_ws_edge_right() {
  echo "$(($(ws_edge_right) - $(win_edge_right)))"
}

# Window X and Y coordinate translations

win_x_moves_left() {
  echo "$(($(win_edge_left) - 128))"
}

win_x_moves_right() {
  echo "$(($(win_edge_left) + 128))"
}

win_y_moves_up() {
  echo "$(($(win_edge_top) - 128))"
}

win_y_moves_down() {
  echo "$(($(win_edge_top) + 128))"
}

win_x_snaps_left() {
  ws_edge_left
}

win_x_snaps_right() {
  echo "$(($(out_edge_right) - $(win_width)))"
}

win_y_snaps_top() {
  ws_edge_top
}

win_y_snaps_bottom() {
  echo "$(($(ws_edge_bottom) - $(win_height)))"
}

win_x_stays() {
  win_edge_left
}

win_y_stays() {
  win_edge_top
}

win_x_snaps_out_right() {
  ws_edge_right
}

win_x_snaps_out_left() {
  echo "$(($(out_edge_left) - $(win_width)))"
}

win_y_snaps_out_top() {
  echo "$(($(out_edge_top) - $(win_height)))"
}

win_y_snaps_out_bottom() {
  out_edge_bottom
}

# Window manager edge snap actions

win_snaps_top() {
  exec i3-msg -q "move absolute position $(win_x_stays) $(win_y_snaps_top)"
}

win_snaps_bottom() {
  exec i3-msg -q "move absolute position $(win_x_stays) $(win_y_snaps_bottom)"
}

win_snaps_left() {
  exec i3-msg -q "move absolute position $(win_x_snaps_left) $(win_y_stays)"
}

win_snaps_right() {
  exec i3-msg -q "move absolute position $(win_x_snaps_right) $(win_y_stays)"
}

win_snaps_out_top() {
  exec i3-msg -q "move absolute position $(win_x_stays) $(win_y_snaps_out_top)"
}

win_snaps_out_bottom() {
  exec i3-msg -q "move absolute position $(win_x_stays) $(win_y_snaps_out_bottom)"
}

win_snaps_out_left() {
  exec i3-msg -q "move absolute position $(win_x_snaps_out_left) $(win_y_stays)"
}

win_snaps_out_right() {
  exec i3-msg -q "move absolute position $(win_x_snaps_out_right) $(win_y_stays)"
}

# Window moving actions

win_moves_down() {
  exec i3-msg -q "move absolute position $(win_x_stays) $(win_y_moves_down)"
}

win_moves_up() {
  exec i3-msg -q "move absolute position $(win_x_stays) $(win_y_moves_up)"
}

win_moves_left() {
  exec i3-msg -q "move absolute position $(win_x_moves_left) $(win_y_stays)"
}

win_moves_right() {
  exec i3-msg -q "move absolute position $(win_x_moves_right) $(win_y_stays)"
}

if [ "$win_type" != "floating_con" ]; then exec i3-msg -q "floating enable"; fi

case "$direction" in
  "up")
    if [ "$(win_edge_bottom)" -gt "$(ws_edge_bottom)" ]; then
      win_snaps_bottom
    fi

    if [ "$(win_edge_top)" -le "$(ws_edge_top)" ]; then
      win_snaps_out_top
    fi

    win_snaps_top
  ;;
  "down")
    if [ "$(win_edge_top)" -lt "$(ws_edge_top)" ]; then
      win_snaps_top
    fi

    if [ "$(win_edge_bottom)" -ge "$(ws_edge_bottom)" ]; then
      win_snaps_out_bottom
    fi

    win_snaps_bottom
  ;;
  "left")
    if [ "$(win_edge_right)" -gt "$(ws_edge_right)" ]; then
      win_snaps_right
    fi

    if [ "$(win_edge_left)" -le "$(ws_edge_left)" ]; then
      win_snaps_out_left
    fi

    win_snaps_left
  ;;
  "right")
    if [ "$(win_edge_left)" -lt "$(ws_edge_left)" ]; then
      win_snaps_left
    fi

    if [ "$(win_edge_right)" -ge "$(ws_edge_right)" ]; then
      win_snaps_out_right
    fi

    win_snaps_right
  ;;
  *)
    exit "1"
  ;;
esac

