#!/usr/bin/env sh
set -eu
wm="${WAYLAND_DISPLAY:+"sway"}"
wm="${wm:-"i3"}"

case "$wm" in
  "sway")
    wm_cmd="swaymsg"
    is_floating_cmd="is_floating_sway"
  ;;
  "i3")
    wm_cmd="i3-msg"
    is_floating_cmd="is_floating_i3"
  ;;
esac

# Window properties

win_height() {
  c_win_height="$(
    case "$wm" in
      "sway")
        echo "$((win_rect_height + win_deco_rect_height))"
      ;;
      "i3")
        echo "$win_rect_height"
      ;;
    esac
  )"

  echo "$c_win_height"
}

win_width() {
  c_win_width="$win_rect_width"

  echo "$c_win_width"
}

win_edge_left() {
  c_win_rect_x="$win_rect_x"

  echo "$c_win_rect_x"
}

win_edge_right() {
  c_win_edge_right="$((
    $(win_edge_left) + $(win_width)
  ))"

  echo "$c_win_edge_right"
}

win_edge_top() {
  c_win_edge_top="$(
    case "$wm" in
      "sway")
        echo "$((win_rect_y - win_deco_rect_height))"
      ;;
      "i3")
        echo "$win_rect_y"
      ;;
    esac
  )"

  echo "$c_win_edge_top"
}

win_edge_bottom() {
  c_win_edge_bottom="$((
    $(win_edge_top) + $(win_height)
  ))"

  echo "$c_win_edge_bottom"
}

# Output properties

out_height() {
  c_out_height="$out_rect_height"

  echo "$c_out_height"
}

out_width() {
  c_out_width="$out_rect_width"

  echo "$c_out_width"
}

out_edge_left() {
  c_out_edge_left="$out_rect_x"

  echo "$c_out_edge_left"
}

out_edge_right() {
  c_out_edge_right="$((
    $(out_edge_left) + $(out_width)
  ))"

  echo "$c_out_edge_right"
}

out_edge_top() {
  c_out_edge_top="$out_rect_y"

  echo "$c_out_edge_top"
}

out_edge_bottom() {
  c_out_edge_bottom="$((
    $(out_edge_top) + $(out_height)
  ))"

  echo "$c_out_edge_bottom"
}

# Workspace properties

ws_height() {
  c_ws_height="$ws_rect_height"

  echo "$c_ws_height"
}

ws_width() {
  c_ws_width="$ws_rect_width"

  echo "$c_ws_width"
}

ws_edge_left() {
  c_ws_edge_left="$ws_rect_x"

  echo "$c_ws_edge_left"
}

ws_edge_right() {
  c_ws_edge_right="$((
    $(ws_edge_left) + $(ws_width)
  ))"

  echo "$c_ws_edge_right"
}

ws_edge_top() {
  c_ws_edge_top="$ws_rect_y"

  echo "$c_ws_edge_top"
}

ws_edge_bottom() {
  c_ws_edge_bottom="$((
    $(ws_edge_top) + $(ws_height)
  ))"

  echo "$c_ws_edge_bottom"
}

## Window snapping vs. step moving workspace edge boundaries

ws_edge_thres_left() {
  c_ws_edge_thres_left="$((
    $(ws_edge_left) + ws_edge_thres_x
  ))"

  echo "$c_ws_edge_thres_left"
}

ws_edge_thres_right() {
  c_ws_edge_thres_right="$((
    $(ws_edge_right) - ws_edge_thres_x
  ))"

  echo "$c_ws_edge_thres_right"
}

ws_edge_thres_top() {
  c_ws_edge_thres_top="$((
    $(ws_edge_top) + ws_edge_thres_y
  ))"

  echo "$c_ws_edge_thres_top"
}

ws_edge_thres_bottom() {
  c_ws_edge_thres_bottom="$((
    $(ws_edge_bottom) - ws_edge_thres_y
  ))"

  echo "$c_ws_edge_thres_bottom"
}

# Window single X and Y coordinate translations

win_x_snaps_left() {
  ws_edge_left
}

win_x_snaps_right() {
  echo "$(($(ws_edge_right) - $(win_width)))"
}

win_y_snaps_top() {
  ws_edge_top
}

win_y_snaps_bottom() {
  echo "$(($(ws_edge_bottom) - $(win_height)))"
}

win_x_stays() {
  win_edge_left
}

win_y_stays() {
  win_edge_top
}

win_x_snaps_out_right() {
  out_edge_right
}

win_x_snaps_out_left() {
  echo "$(($(out_edge_left) - $(win_width)))"
}

win_y_snaps_out_top() {
  echo "$(($(out_edge_top) - $(win_height)))"
}

win_y_snaps_out_bottom() {
  out_edge_bottom
}

win_x_moves_left() {
  echo "$(($(win_edge_left) - move_step_x))"
}

win_x_moves_right() {
  echo "$(($(win_edge_left) + move_step_x))"
}

win_y_moves_up() {
  echo "$(($(win_edge_top) - move_step_y))"
}

win_y_moves_down() {
  echo "$(($(win_edge_top) + move_step_y))"
}

# Window manager edge snap actions

win_snaps_top() {
  $wm_cmd -q "move absolute position $(win_x_stays) $(win_y_snaps_top)"
}

win_snaps_bottom() {
  $wm_cmd -q "move absolute position $(win_x_stays) $(win_y_snaps_bottom)"
}

win_snaps_left() {
  $wm_cmd -q "move absolute position $(win_x_snaps_left) $(win_y_stays)"
}

win_snaps_right() {
  $wm_cmd -q "move absolute position $(win_x_snaps_right) $(win_y_stays)"
}

win_snaps_out_top() {
  $wm_cmd -q "move absolute position $(win_x_stays) $(win_y_snaps_out_top)"
}

win_snaps_out_bottom() {
  $wm_cmd -q "move absolute position $(win_x_stays) $(win_y_snaps_out_bottom)"
}

win_snaps_out_left() {
  $wm_cmd -q "move absolute position $(win_x_snaps_out_left) $(win_y_stays)"
}

win_snaps_out_right() {
  $wm_cmd -q "move absolute position $(win_x_snaps_out_right) $(win_y_stays)"
}

# Window moving actions

win_moves_down() {
  $wm_cmd -q "move absolute position $(win_x_stays) $(win_y_moves_down)"
}

win_moves_up() {
  $wm_cmd -q "move absolute position $(win_x_stays) $(win_y_moves_up)"
}

win_moves_left() {
  $wm_cmd -q "move absolute position $(win_x_moves_left) $(win_y_stays)"
}

win_moves_right() {
  $wm_cmd -q "move absolute position $(win_x_moves_right) $(win_y_stays)"
}

is_floating_sway() {
  if [ "$win_type" != "floating_con" ]; then
    return "1"
  fi
}

is_floating_i3() {
  case "$win_floating" in
    *"_off")
      return "1"
    ;;
  esac
}

# needs to issue 1 atomic command for x y

# AS - pos window side A (top or left)
# BS - pos window side B (bottom or right)
# AZ - pos workspace side A (top or left)
# BZ - pos workspace side B (bottom or right)
# AO - pos workspace side A outer snap threshold
# AI - pos workspace side A inner snap threshold
# AO - pos workspace side B outer snap threshold
# AI - pos workspace side B inner snap threshold
# S - width workspace safe (AI to BI)

# AO - AZ - AI - S - BI - BZ - BO

# AS in AI == AS >= AZ && AS < AI
# AS in AO == AS >= AO && AS < AZ
# AS in BI == AS >= BI && AS < BZ
# AS in BO == AS >= BZ && AS < BO
# AS in S == AS >= AI && AS < BI
# AS out AO == AS < AO
# AS out BO == AS >= BO
# BS in AI == BS >= AZ && BS < AI
# BS in AO == BS >= AO && BS < AZ
# BS in BI == BS < BZ && BS >= BI
# BS in BO == BS < BO && BS >= BZ
# BS in S == BS >= AI && BS < BI
# BS out AO == BS < AO
# BS out BO == BS >= BO

# A() == AS = AZ
# B() == BS = BZ - BS - AS
# N() == AS = AS

# ------------------------------------------------

# AS in BO ; BS out BO ; N()
# AS in BO ; BS in BO ; B()

# AS out BO ; BS out BO ; N()

# AS in S ; BS in S ; N()
# AS in S ; BS out BO ; N()
# AS in S ; BS in BI ; B()
# AS in S ; BS in BO ; B()

# AS out AO ; BS in AI ; N()
# AS out AO ; BS in AO ; N()
# AS out AO ; BS in S ; N()
# AS out AO ; BS out AO ; N()
# AS out AO ; BS out BO ; N()
# AS out AO ; BS in BI ; B()
# AS out AO ; BS in BO ; B()

# BS on BZ ; N()
# AS on AZ ; N()

# AS in AI ; BS in BI ; AS - AZ <= BZ - BS ? A() : B()
# AS in AI ; BS in BO ; AS - AZ <= BS - BZ ? A() : B()
# AS in AI ; BS in AI ; A
# AS in AI ; BS in S ; A
# AS in AI ; BS out BO ; A

# AS in AO ; BS in BI ; AS - AZ <= BZ - BS ? A() : B()
# AS in AO ; BS in BO ; AS - AZ <= BS - BZ ? A() : B()
# AS in AO ; BS in AI ; A()
# AS in AO ; BS in S ; A()
# AS in AO ; BS out BO ; A()
# AS in AO ; BS in AO ; A()

# AS in BI ; BS out BO ; N()
# AS in BI ; BS in BI ; B()
# AS in BI ; BS in BO ; B()

a_or_b() {
  AS="$1" BS="$2" AZ="$3" BZ="$4" AI="$5" BI="$6" AO="$7" BO="$8"
}

snap() {
  if \
    [ "$(win_edge_top)" -gt "$(ws_edge_top)" ] && \
    [ "$(win_edge_top)" -le "$(ws_edge_thres_top)" ]
  then
    win_snaps_top
  fi

  if \
    [ "$(win_edge_bottom)" -lt "$(ws_edge_bottom)" ] && \
    [ "$(win_edge_bottom)" -gt "$(ws_edge_thres_bottom)" ]
  then
    win_snaps_bottom
  fi

  if \
    [ "$(win_edge_left)" -gt "$(ws_edge_left)" ] && \
    [ "$(win_edge_left)" -le "$(ws_edge_thres_left)" ]
  then
    win_snaps_left
  fi

  if \
    [ "$(win_edge_right)" -lt "$(ws_edge_right)" ] && \
    [ "$(win_edge_right)" -gt "$(ws_edge_thres_right)" ]
  then
    win_snaps_right
  fi
}

while true; do
  ws="$(
    $wm_cmd -t "get_workspaces" | jq -r \
    ".[] | select(.focused == true) | .rect.x, .rect.y, .rect.width, .rect.height, .output"
  )"

  ws_rect_x="$(              echo "$ws" | sed  "1q;d")"
  ws_rect_y="$(              echo "$ws" | sed  "2q;d")"
  ws_rect_width="$(          echo "$ws" | sed  "3q;d")"
  ws_rect_height="$(         echo "$ws" | sed  "4q;d")"
  ws_output="$(              echo "$ws" | sed  "5q;d")"

  out_rect="$(
    $wm_cmd -t "get_outputs"    | jq -r \
    ".[] | select(.name == \"${ws_output}\").rect | .x, .y, .width, .height"
  )"

  out_rect_x="$(       echo "$out_rect" | sed  "1q;d")"
  out_rect_y="$(       echo "$out_rect" | sed  "2q;d")"
  out_rect_width="$(   echo "$out_rect" | sed  "3q;d")"
  out_rect_height="$(  echo "$out_rect" | sed  "4q;d")"

  win="$(
    $wm_cmd -t "get_tree"       | jq -r \
    ".. | select(.type?) | select(.focused == true) | .type, .floating, .fullscreen_mode, .rect.x, .rect.y, .rect.width, .rect.height, .window_rect.x, .window_rect.y, .window_rect.width, .window_rect.height, .deco_rect.x, .deco_rect.y, .deco_rect.width, .deco_rect.height, .geometry.x, .geometry.y, .geometry.width, .geometry.height"
  )"

  win_type="$(              echo "$win" | sed  "1q;d")"
  win_floating="$(          echo "$win" | sed  "2q;d")" # i3
  win_fullscreen_mode="$(   echo "$win" | sed  "3q;d")"
  win_rect_x="$(            echo "$win" | sed  "4q;d")"
  win_rect_y="$(            echo "$win" | sed  "5q;d")"
  win_rect_width="$(        echo "$win" | sed  "6q;d")"
  win_rect_height="$(       echo "$win" | sed  "7q;d")"
  # win_window_rect_x="$(     echo "$win" | sed  "8q;d")"
  # win_window_rect_y="$(     echo "$win" | sed  "9q;d")"
  # win_window_rect_width="$( echo "$win" | sed "10q;d")"
  # win_window_rect_height="$(echo "$win" | sed "11q;d")"
  # win_deco_rect_x="$(       echo "$win" | sed "12q;d")"
  # win_deco_rect_y="$(       echo "$win" | sed "13q;d")"
  # win_deco_rect_width="$(   echo "$win" | sed "14q;d")"
  win_deco_rect_height="$(  echo "$win" | sed "15q;d")"
  # win_geometry_x="$(        echo "$win" | sed "16q;d")"
  # win_geometry_y="$(        echo "$win" | sed "17q;d")"
  # win_geometry_width="$(    echo "$win" | sed "18q;d")"
  # win_geometry_height="$(   echo "$win" | sed "19q;d")"

  # TODO: all the output, workspace and window properties can be probably precomputed faster in jq queries

  # Window moving properties

  move_step_x="$((ws_rect_width / 20))"
  move_step_y="$((ws_rect_height / 20))"
  ws_edge_thres_x="$move_step_x"
  ws_edge_thres_y="$move_step_y"

  if [ "$win_fullscreen_mode" = "0" ] && "$is_floating_cmd"; then
    snap
  fi

  echo "$win_type"

  sleep 1
done
