#!/usr/bin/env sh
set -eu
wm="${WAYLAND_DISPLAY:+"sway"}"
wm="${wm:-"i3"}"

case "$wm" in
  "sway")
    wm_cmd="swaymsg"
    is_win_floating_cmd="is_win_floating_sway"
    win_height_cmd="win_height_sway"
    win_edge_top_cmd="win_edge_top_sway"
  ;;
  "i3")
    wm_cmd="i3-msg"
    is_win_floating_cmd="is_win_floating_i3"
    win_height_cmd="win_height_i3"
    win_edge_top_cmd="win_edge_top_i3"
  ;;
esac

ws_thr_x="128"
ws_thr_y="128"

# Window properties

win_height_sway() { echo "$((win_rect_height + win_deco_rect_height))"; }
win_height_i3() { echo "$win_rect_height"; }

win_edge_top_sway() { echo "$((win_rect_y - win_deco_rect_height))"; }
win_edge_top_i3() { echo "$win_rect_y"; }

# Workspace properties

ws_edge_right() { echo "$((ws_rect_x + ws_rect_width))"; }
ws_edge_bottom() { echo "$((ws_rect_y + ws_rect_height))"; }

## Workspace edge snap thrhold boundaries

ws_thr_left_i() { echo "$((ws_rect_x + ws_thr_x))"; }
ws_thr_right_i() { echo "$(($(ws_edge_right) - ws_thr_x))"; }
ws_thr_top_i() { echo "$((ws_rect_y + ws_thr_y))"; }
ws_thr_bottom_i() { echo "$(($(ws_edge_bottom) - ws_thr_y))"; }
ws_thr_left_o() { echo "$((ws_rect_x - ws_thr_x))"; }
ws_thr_right_o() { echo "$(($(ws_edge_right) + ws_thr_x))"; }
ws_thr_top_o() { echo "$((ws_rect_y - ws_thr_y))"; }
ws_thr_bottom_o() { echo "$(($(ws_edge_bottom) + ws_thr_y))"; }

# Is floating
is_win_floating_sway() {
  if [ "$win_type" != "floating_con" ]; then return "1"; fi
}

is_win_floating_i3() {
  case "$win_floating" in
    *"_off")
      return "1"
    ;;
  esac
}

# AS - pos window side A (top or left)
# BS - pos window side B (bottom or right)
# AZ - pos workspace side A (top or left)
# BZ - pos workspace side B (bottom or right)
# AO - pos workspace side A outer snap threshold
# AI - pos workspace side A inner snap threshold
# AO - pos workspace side B outer snap threshold
# AI - pos workspace side B inner snap threshold
# S  - width workspace safe (AI to BI)

# AO - AZ - AI - S - BI - BZ - BO

# AS on AZ ; N
# BS on BZ ; N
# AS in S ; BS in S ; N
# AS in S ; BS out BO ; N
# AS in S ; BS in BI ; B
# AS in S ; BS in BO ; B
# AS in BO ; BS out BO ; N
# AS in BO ; BS in BO ; B
# AS out BO ; BS out BO ; N
# AS out AO ; BS in AI ; N
# AS out AO ; BS in AO ; N
# AS out AO ; BS in S ; N
# AS out AO ; BS out AO ; N
# AS out AO ; BS out BO ; N
# AS out AO ; BS in BI ; B
# AS out AO ; BS in BO ; B
# AS in AI ; BS in BI ; AS - AZ <= BZ - BS ? A : B
# AS in AI ; BS in BO ; AS - AZ <= BS - BZ ? A : B
# AS in AI ; BS in AI ; A
# AS in AI ; BS in S ; A
# AS in AI ; BS out BO ; A
# AS in AO ; BS in BI ; AS - AZ <= BZ - BS ? A : B
# AS in AO ; BS in BO ; AS - AZ <= BS - BZ ? A : B
# AS in AO ; BS in AI ; A
# AS in AO ; BS in S ; A
# AS in AO ; BS out BO ; A
# AS in AO ; BS in AO ; A
# AS in BI ; BS out BO ; N
# AS in BI ; BS in BI ; B
# AS in BI ; BS in BO ; B

AS_on_AZ()  { test "$AS" -eq "$AZ"; }
BS_on_BZ()  { test "$BS" -eq "$BZ"; }
AS_in_AI()  { test "$AS" -ge "$AZ" && test "$AS" -lt "$AI"; }
AS_in_AO()  { test "$AS" -ge "$AO" && test "$AS" -lt "$AZ"; }
AS_in_BI()  { test "$AS" -ge "$BI" && test "$AS" -lt "$BZ"; }
AS_in_BO()  { test "$AS" -ge "$BZ" && test "$AS" -lt "$BO"; }
AS_in_S()   { test "$AS" -ge "$AI" && test "$AS" -lt "$BI"; }
AS_out_AO() { test "$AS" -lt "$AO"; }
AS_out_BO() { test "$AS" -ge "$BO"; }
BS_in_AI()  { test "$BS" -ge "$AZ" && test "$BS" -lt "$AI"; }
BS_in_AO()  { test "$BS" -ge "$AO" && test "$BS" -lt "$AZ"; }
BS_in_BI()  { test "$BS" -lt "$BZ" && test "$BS" -ge "$BI"; }
BS_in_BO()  { test "$BS" -lt "$BO" && test "$BS" -ge "$BZ"; }
BS_in_S()   { test "$BS" -ge "$AI" && test "$BS" -lt "$BI"; }
BS_out_AO() { test "$BS" -lt "$AO"; }
BS_out_BO() { test "$BS" -ge "$BO"; }

A() { echo "$AZ"; }
B() { echo "$((AS + BZ - BS))"; }
N() { echo "$AS"; }

A_or_B() {
  AS="$1" BS="$2" AZ="$3" BZ="$4" AI="$5" BI="$6" AO="$7" BO="$8"

  if AS_on_AZ || BS_on_BZ; then N; return; fi

  if AS_in_S; then
    if BS_in_S || BS_out_BO; then N; return; fi
    if BS_in_BI || BS_in_BO; then B; return; fi
  fi

  if AS_in_BO; then
    if BS_out_BO; then N; return; fi
    if BS_in_BO; then B; return; fi
  fi

  if AS_out_BO && BS_out_BO; then N; return; fi

  if AS_out_AO; then
    if BS_in_AI || BS_in_AO || BS_in_S || BS_out_AO || BS_out_BO; then N; return; fi
    if BS_in_BI || BS_in_BO; then B; return; fi
  fi

  if AS_in_AI || AS_in_AO; then
    if BS_in_BI; then
      if [ "$((AS - AZ))" -le "$((BZ - BS))" ]; then A; return; else B; return; fi
    fi

    if BS_in_BO; then
      if [ "$((AS - AZ))" -le "$((BS - BZ))" ]; then A; return; else B; return; fi
    fi

    if BS_in_AI || BS_in_S || BS_out_BO; then A; return; fi
  fi

  if AS_in_AO && BS_out_AO; then A; return; fi

  if AS_in_BI; then
    if BS_out_BO; then N; return; fi
    if BS_in_BI || BS_in_BO; then B; return; fi
  fi
}

while true; do
  win="$(
    $wm_cmd -t "get_tree" | jq -r \
    ".. | select(.type?) | select(.focused) | .type, .floating, .fullscreen_mode, .rect.x, .rect.y, .rect.width, .rect.height, .deco_rect.height"
  )"

  win_type="$(              echo "$win" | sed "1q;d")"
  win_floating="$(          echo "$win" | sed "2q;d")" # i3
  win_fullscreen_mode="$(   echo "$win" | sed "3q;d")"

  if "$is_win_floating_cmd" && [ "$win_fullscreen_mode" = "0" ]; then
    ws="$(
      $wm_cmd -t "get_workspaces" | jq -r \
      ".[] | select(.focused) | .rect.x, .rect.y, .rect.width, .rect.height"
    )"

    ws_rect_x="$(              echo "$ws" | sed  "1q;d")"
    ws_rect_y="$(              echo "$ws" | sed  "2q;d")"
    ws_rect_width="$(          echo "$ws" | sed  "3q;d")"
    ws_rect_height="$(         echo "$ws" | sed  "4q;d")"

    win_rect_x="$(            echo "$win" | sed "4q;d")"
    win_rect_y="$(            echo "$win" | sed "5q;d")"
    win_rect_width="$(        echo "$win" | sed "6q;d")"
    win_rect_height="$(       echo "$win" | sed "7q;d")"
    win_deco_rect_height="$(  echo "$win" | sed "8q;d")"

    $wm_cmd -q "move absolute position $(A_or_B "$win_rect_x" "$((win_rect_x + win_rect_width))" "$ws_rect_x" "$(ws_edge_right)" "$(ws_thr_left_i)" "$(ws_thr_right_i)" "$(ws_thr_left_o)" "$(ws_thr_right_o)") $(A_or_B "$("$win_edge_top_cmd")" "$(($("$win_edge_top_cmd") + $("$win_height_cmd")))" "$ws_rect_y" "$(ws_edge_bottom)" "$(ws_thr_top_i)" "$(ws_thr_bottom_i)" "$(ws_thr_top_o)" "$(ws_thr_bottom_o)")"
  fi

  sleep 1
done
