#!/usr/bin/env sh
set -eu

# TODO
# - workspace, not output relative size
# - try to fit window x and y "geometry" ratio within ws x y boundaries
#   - (geometry - object - The natural geometry of the contents if it were to size itself)
#   - first try without padding?

ws_out_name="$(i3-msg -t "get_workspaces" | jq -r ".[] | select(.focused == true) | .output")"
out="$(i3-msg -t get_outputs | jq ".[] | select(.name == \"${ws_out_name}\").rect | .width,.height")"
out_width="$(echo "$out" | sed  "1q;d")"
out_height="$(echo "$out" | sed  "2q;d")"

max_width="1920"
max_height="1280"
padding_percent="0.075"

padding="$(echo "(${padding_percent} * ${out_width} + ${padding_percent} * ${out_height}) / 2" | bc)"
width="$(echo "${out_width} - ${padding}" | bc)"
height="$(echo "${out_height} - ${padding}" | bc)"

if [ "$width" -gt "$max_width" ]; then
  width="$max_width"
fi

if [ "$height" -gt "$max_height" ]; then
  height="$max_height"
fi

i3-msg -q "floating toggle; resize set width ${width} height ${height}; move position center"
