#!/usr/bin/env sh

[ "$1" = "" ] && exit 1

outputs_count="$(i3-msg -t get_outputs | jq 'length')"

[ "$outputs_count" = "1" ] && {
  case "$1" in
    "left") exec i3-msg workspace prev
    ;;
    "right") exec i3-msg workspace next
    ;;
    *) exit 1;
    ;;
  esac
}

exec i3-msg focus output "$1"
