#!/usr/bin/env sh
set -eu

if [ -z "${1:-""}" ]; then
  exit "1"
fi

outputs_count="$(i3-msg -t get_outputs | jq '[.[] | select(.active == true)] | length')"

case "$1" in
  "left")
    if [ "$outputs_count" = "1" ]; then 
      exec i3-msg -q workspace prev
    fi

    exec i3-msg -q focus output left
  ;;
  "right")
    if [ "$outputs_count" = "1" ]; then 
      exec i3-msg -q workspace next
    fi

    exec i3-msg -q focus output right
  ;;
  *)
    exit "1"
  ;;
esac
