#!/usr/bin/env sh

wm="$1"
[ -z "$wm" ] && [ "$WAYLAND_DISPLAY" ] && wm="sway"
[ -z "$wm" ] && wm="i3"

win_title="\033]0;${wm} window manager key mappings\007"

exec $TERMINAL -e "$SHELL" -c "echo -n \"$win_title\"; \${XDG_DATA_HOME:-\$HOME/.local/share}/i3/i3_key_mappings ${wm}| \${PAGER}"
