#!/usr/bin/env sh
set -eu
export LC_ALL="C"

wm="${1:-""}"
wm="${WAYLAND_DISPLAY:+"sway"}"
wm="${wm:-"i3"}"

win_title="\033]0;\"${wm}\" key mappings\007"

exec $TERMINAL -e "$SHELL" -c "echo -n \"$win_title\"; \${XDG_DATA_HOME:-\$HOME/.local/share}/i3/i3_key_mappings ${wm}| \${PAGER}"
