#!/usr/bin/env sh

echo "$(< ${XDG_CONFIG_HOME:-$HOME/.config}/i3/config)" \
  | sed 's/  */ /g' \
  | sed -z 's/\\\n//g' \
  | grep "bindsym" \
  | sed 's/bindsym //g' \
  | sed 's/--whole-window //g' \
  | sed 's/--no-startup-id //g' \
  | sed 's/ exec / /g' \
  | sed 's/^ / ->   /g' \
  | column -t -s' ' -l 2
