#!/usr/bin/env sh

# TODO: explictly check if i3 or Sway session in focus so both don't interfere

menu="dmenu"
[ -z "$DISPLAY" ] && [ "$WAYLAND_DISPLAY" ] && menu="wmenu"

exec i3-msg move container to workspace "$(i3-msg -t get_workspaces | jq '.[].name' -r | "$menu" -p "Move window to workspace:")"
