#!/usr/bin/env sh
set -eu

# If the current workspace is named "2":
#
# | Input       | The new name |
# | ----------- | ------------ |
# | 3           | 3            |
# | new name    | 2: new name  |
# | 3:new name  | 3: new name  |
# | 3: new name | 3: new name  |
# | 3new name   | 2: 3new name |

wm="${WAYLAND_DISPLAY:+"sway"}"
wm="${wm:-"i3"}"

case "$wm" in
  "sway")
    wm_cmd="swaymsg"
    cmd_menu="wmenu"
  ;;
  "i3")
    wm_cmd="i3-msg"
    cmd_menu="dmenu"
  ;;
  *)
    exit "1"
  ;;
esac

ws="$(
  $wm_cmd -t "get_workspaces" | jq -r \
  ".[] | select(.focused == true) | .num, .name"
)"
ws_num="$( echo "$ws" | sed  "1q;d")"
ws_name="$(echo "$ws" | sed  "2q;d")"

ws_name_input="$(echo $("$@" | "$cmd_menu" -p "Rename workspace \"${ws_name}\":"))"

[ "$ws_name_input" ] || exit "2"

name_new_is_num="0"

set -e
test "$ws_name_input" -eq "$ws_name_input" 2> /dev/null && name_new_is_num="1"
set +e

if [ "$name_new_is_num" = "1" ]; then
  exec i3-msg -q rename workspace "$ws_name" to "$ws_name_input"
fi

# TODO: swap existing ws with the specified number

ws_name_new_name_num="$(echo "$ws_name_input" | cut -s -d":" -f "1")"

if [ -z "$ws_name_new_name_num" ]; then
  exec i3-msg -q rename workspace to "${ws_num}: ${ws_name_input}"
fi

ws_name_new_name_title="$(echo "$ws_name_input" | cut -s -d":" -f "2")"

if [ -z "$(echo $ws_name_new_name_title)" ]; then
  exit "2"
fi

exec i3-msg -q rename workspace to "${ws_name_new_name_num}: ${ws_name_new_name_title}"
