#!/usr/bin/env sh

# Assumes the integer index only name workspaces.

wss="$(i3-msg -t get_workspaces | jq 'map({num,focused,representation})')"

# In Sway checking if workspace is already empty. i3 containers have no 'representation' property.
if [ "${WAYLAND_DISPLAY:-""}" ] && [ "$(echo "$wss" | jq -r ".[[.[].focused] | index(true)].representation")" = "null" ]; then
  exit "1"
fi

wss_num="$(echo $(echo "$wss" | jq '.[].num' -r | sort))"

pre_wsn="$(($(echo "$wss_num" | cut -d" " -f 1) - 1))"

if [ "$pre_wsn" -ge 1 ]; then
  i3-msg -q "move container to workspace number 1; workspace number 1"
fi

for wsn in $wss_num; do
  if [ $((pre_wsn + 1)) -ne "$wsn" ]; then
    exec i3-msg -q "move container to workspace number $((pre_wsn + 1)); workspace number $((pre_wsn + 1))"
  fi

  pre_wsn="$wsn"
done

i3-msg -q "move container to workspace number $((wsn + 1)); workspace number $((wsn + 1))"
