#!/usr/bin/env sh

wm="${WAYLAND_DISPLAY:+"sway"}"
wm="${wm:-"i3"}"

case "$wm" in
  "sway")
    wm_cmd="swaymsg"
  ;;
  "i3")
    wm_cmd="i3-msg"
  ;;
esac

wss="$($wm_cmd -t get_workspaces | jq 'map({num,focused,representation})')"

# In Sway - checking if workspace is already empty.
# In i3 the containers have no 'representation' property.
if [ "${WAYLAND_DISPLAY:-""}" ] && [ "$(echo "$wss" | jq -r ".[[.[].focused] | index(true)].representation")" = "null" ]; then
  exit "1"
fi

wss_num="$(echo "$wss" | jq -r '.[].num' | sort | tr '\n' ' ')"
pre_wsn="$(("${wss_num%% *}" - 1))"

if [ "$pre_wsn" -ge 1 ]; then
  $wm_cmd -q "move container to workspace number 1; workspace number 1"
fi

for wsn in $wss_num; do
  if [ "$((pre_wsn + 1))" -ne "$wsn" ]; then
    exec $wm_cmd -q "move container to workspace number $((pre_wsn + 1)); workspace number $((pre_wsn + 1))"
  fi

  pre_wsn="$wsn"
done

exec $wm_cmd -q "move container to workspace number $((wsn + 1)); workspace number $((wsn + 1))"
