#!/usr/bin/env sh
set -eu

# Assumes the integer index only name workspaces.

wss="$(i3-msg -t get_workspaces | jq 'map({num,focused,representation})')"

# In Sway checking if workspace is already empty. i3 containers have no 'representation' property.
if [ "${WAYLAND_DISPLAY:-""}" ] && [ "$(echo "$wss" | jq -r ".[[.[].focused] | index(true)].representation")" = "null" ]; then
  exec i3-msg -q workspace back_and_forth
fi

wss_num="$(echo "$wss" | jq '.[].num' -r | sort | tr '\n' ' ')"

pre_wsn="$(($(echo "$wss_num" | cut -d" " -f 1) - 1))"

if [ "$pre_wsn" -ge 1 ]; then
  exec i3-msg -q workspace 1
fi

for wsn in $wss_num; do
  if [ $((pre_wsn + 1)) -ne "$wsn" ]; then
    exec i3-msg -q workspace "$((pre_wsn + 1))"
  fi

  pre_wsn="$wsn"
done

i3-msg -q workspace "$((wsn + 1))"
