#!/usr/bin/env sh

# Assumes the integer index only name workspaces.

workspaces="$(echo $(i3-msg -t get_workspaces | jq '.[].name' -r))"

pre_ws="$(($(echo "$workspaces" | cut -d" " -f 1) - 1))"

[ "$pre_ws" -ge 1 ] && exec i3-msg workspace 1

for ws in $workspaces; do
  [ $((pre_ws + 1)) -ne "$ws" ] && exec i3-msg workspace $((pre_ws + 1))
  pre_ws="$ws"
done

i3-msg workspace "$((ws + 1))"
