#!/usr/bin/env sh
set -eu

# TODO: support for multi-monitor setups
# TODO: handling named workspaces without the index prefix

# "next" or "prev"
direction="${1:-next}"

[ "$direction" != "next" ] && [ "$direction" != "prev" ] && exit 1

wss="$(i3-msg -t get_workspaces | jq -r 'map({num: .num,name: .name,focused: .focused})')"
ws_i="$(echo "$wss" | jq -r '[.[].focused] | index(true)')"
ws="$(echo "$wss" | jq -r ".[$ws_i]")"
ws_num="$(echo "$ws" | jq -r ".num")"
ws_name="$(echo "$ws" | jq -r ".name")"
ws_name_no_num="$(echo "$ws_name" | cut -d":" -f "2")"

case "$direction" in
  "next") 
    ws_beside="$(echo "$wss" | jq -r ".[$((ws_i + 1))]")" 
    num_beside="$((ws_num + 1))"
    ;;
  "prev") 
    ws_beside="$(echo "$wss" | jq -r ".[$((ws_i - 1))]")" 
    num_beside="$((ws_num - 1))"
    ;;
esac

[ "$ws_beside" != "null" ] && {
  ws_tmp_name="-"
  ws_beside_num="$(echo "$ws_beside" | jq -r ".num")"

  [ "$ws_beside_num" = "$num_beside" ] && {
    ws_beside_name="$(echo "$ws_beside" | jq -r ".name")"
    ws_beside_name_no_num="$(echo "$ws_beside_name" | cut -d":" -f "2")"

    i3-msg rename workspace "$ws_beside_name" to "$ws_tmp_name"

    ws_name_new="$num_beside"
    [ "$ws_name_no_num" != "$ws_num" ] && ws_name_new="$num_beside:$ws_name_no_num"

    i3-msg rename workspace "$ws_name" to "$ws_name_new"

    ws_beside_name_new="$ws_num"
    [ "$ws_beside_name_no_num" != "$ws_beside_num" ] && ws_beside_name_new="$ws_num:$ws_beside_name_no_num"

    exec i3-msg rename workspace "$ws_tmp_name" to "$ws_beside_name_new"
  }
}

ws_name_new="$num_beside"
[ "$ws_name_no_num" != "$ws_num" ] && ws_name_new="$num_beside:$ws_name_no_num"

exec i3-msg rename workspace "$ws_name" to "$ws_name_new"
