#!/usr/bin/env sh

# TODO: fix/rewrite (for swaymsg)
# TODO: convert to POSIX sh
# TODO: use getopts
# TODO: use jq

#"-next" or "-prev"
move_direction="${1:--next}"

[ "$move_direction" != "-next" ] && [ "$move_direction" != "-prev" ] && exit 1

workspaces="$(echo $(i3-msg -t get_workspaces | jq '.[].name' -r))"
current_workspace="$(i3-msg -t get_workspaces | jq '.[] | select(.focused == true).name' -r)"

prev="0"

get_prev_workspace() {
  for ws in $workspaces; do
    if [ "$ws" -eq "$current_workspace" ]; then
      echo "$prev"
      return
    fi

    prev="$ws"
  done
}

next="0"

get_next_workspace() {
  for ws in $workspaces; do
    next="$((next + 1))"

    if [ "$i" = "$current_workspace" ]; then
      local next_workspace=${workspaces[$next]}
      break
    fi
  done

  echo "$next_workspace"
}

prev_workspace="$(get_prev_workspace)"
next_workspace="$(get_next_workspace)"

if [ "$move_direction" = "-next" ]; then
  if [ "$next_workspace" != "$((current_workspace + 1))" ]; then
    echo Add new workspace 1 forwards by renaming/addition.

    i3-msg rename workspace "$current_workspace" to "$((current_workspace + 1))"

    exit
  elif [ "$next_workspace" = "$((current_workspace + 1))" ]; then
    echo "Move 1 workspace forwards by swapping workspace contents."

    i3-msg rename workspace "$current_workspace" to "0"
    i3-msg rename workspace "$next_workspace" to "$current_workspace"
    i3-msg rename workspace "0" to "$next_workspace"

    exit
  fi
elif [ "$move_direction" = "-prev" ]; then
  if [ "$prev_workspace" != "$((current_workspace - 1))" ]; then
    echo "Add new workspace 1 backwards by renaming/substraction."

    echo "$current_workspace"
    i3-msg rename workspace "$current_workspace" to "$((current_workspace - 1))"

    exit
  elif [ "$prev_workspace" = "$((current_workspace - 1))" ]; then
    echo "Move 1 workspace backwards by swapping workspace contents."

    i3-msg rename workspace "$current_workspace" to "0"
    i3-msg rename workspace "$prev_workspace" to "$current_workspace"
    i3-msg rename workspace "0" to "$prev_workspace"

    exit
  fi
else
  echo "Invalid argument. Use '-next' or '-prev'."
fi
