#!/usr/bin/env sh
set -euf
NL="
"

if [ "${DISPLAY:-""}" ] && [ -z "${WAYLAND_DISPLAY:-""}" ]; then
  exec "xkill"
fi

win="$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused == true)')"
pid="$(echo "$win" | jq '.pid')"

if [ "$pid" = "null" ]; then
  exit "1"
fi

name="$(echo "$win" | jq '.name')"

details_ps="$(ps --no-headers -p "${pid}" -o "pid,user,group,comm,args" | tr -s " ")"
details_ps="${details_ps%% }"
details_ps="${details_ps## }"

comm="$(echo "$details_ps" | cut -d" " -f4)"

details="Process:${NL}${details_ps}${NL}Window title:${NL}${name}"

printf "%s" "$details" | swaynag -t "warning" -l -b "htop" "htop -p ${pid}" -m "Kill (9) process ${pid} \"${comm}\" of window ${name}?" -Z "Yes" "kill -9 ${pid}"
