#!/usr/bin/env sh
BAT_STYLE="plain"

mime="$(file --mime-type "$(readlink -f "$1")" -b)"

echo "$mime"

case $mime in
  application/eps|application/pdf|application/postscript|application/x-eps|image/x-eps) pdftotext -- "$1" -; exit 1;;
  application/bzip*|application/gzip|application/vnd.rar|application/x-7z-compressed|application/x-rar|application/x-tar|application/x-xz|application/zip) als -- "$1"; exit 1;;
  image/*) chafa --format "symbols" --font-ratio "1/3" --animate "off" --polite "on" --work "1" -s "${2}x${3}" "$1"; exit 1;;
  *opendocument*) odt2txt "$1"; exit 1;;
  application/vnd.sqlite3|application/vnd.sqlite) sqlite3 "$1" '.tables'; exit 1;;
  *) bat --color always -- "$1"; exit 1;;
esac
