#!/usr/bin/env sh
set -eu

fpath="$(readlink -f "$1")"
width_chr="${2:-80}"
height_chr="${3:-120}"
FPATH_THUMB=""

thumb_cache_create() {
  dir_cache_thumb="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumbnails"
  [ -d "$dir_cache_thumb" ] || mkdir -p "$dir_cache_thumb"
  FPATH_THUMB="${dir_cache_thumb}/$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$fpath" | sha256sum | cut -d" " -f1)"
}

mime="$(file --mime-type --brief "$fpath")"

echo "$mime"

case $mime in
  application/eps|application/pdf|application/postscript|application/x-eps|image/x-eps)
    thumb_cache_create

    [ -f "${FPATH_THUMB}.jpg" ] || pdftoppm -jpeg -jpegopt quality=50 -f "1" -singlefile "$1" "$FPATH_THUMB"

    resz_width_chr="$(echo "scale = 0; ${width_chr} * 0.35" | bc)"
    resz_height_chr="$(echo "scale = 0; ${height_chr} * 0.35" | bc)"

    chafa --format "symbols" --font-ratio "1/2" --animate "off" --polite "on" --work "1" -s "${resz_width_chr}x${resz_height_chr}" "${FPATH_THUMB}.jpg"
    echo
    pdfinfo "$fpath"
    echo
    pdftotext -l "2" -nopgbrk -q -- "$fpath" -
  ;;
  application/bzip*|application/gzip|application/vnd.rar|application/x-7z-compressed|application/x-rar|application/x-tar|application/x-xz|application/zip)
    als -- "$fpath"
  ;;
  image/*)
    chafa --format "symbols" --font-ratio "1/2" --animate "off" --polite "on" --work "1" -s "${width_chr}x${height_chr}" "$fpath"
  ;;
  audio/mpeg)
    mpg123-id3dump -- "$fpath"
  ;;
  video/*)
    thumb_cache_create

    [ -f "${FPATH_THUMB}.jpg" ] || ffmpegthumbnailer -i "$1" -o "${FPATH_THUMB}.jpg" -s "0" -q "5"

    chafa --format "symbols" --font-ratio "1/2" --animate "off" --polite "on" --work "1" -s "${width_chr}x${height_chr}" "${FPATH_THUMB}.jpg"
  ;;
  *opendocument*)
    odt2txt "$fpath"
  ;;
  application/vnd.sqlite3|application/vnd.sqlite)
    sqlite3 "$fpath" '.tables'
  ;;
  inode/directory)
    ls -la "$fpath"
  ;;
  *)
    bat --color=always --style=plain -- "$fpath"
  ;;
esac

exit "1"
