#!/usr/bin/env sh

# Merging the xsettingsd common and local configurations

pathd_cfg="${XDG_CONFIG_HOME:-$HOME/.config}/xsettingsd"

pathf_cfg_local="${pathd_cfg}/local.conf"
pathf_cfg_common="${pathd_cfg}/common.conf"
pathf_cfg="${pathd_cfg}/xsettingsd.conf"

if [ -f "$pathf_cfg_local" ]; then
  cfg_local="$(cat "$pathf_cfg_local")"

  echo "$(
    if [ -f "$pathf_cfg_common" ]; then
      while IFS=' ' read -r key val; do
        if [ -z "${key##\#*}" ]; then
          continue
        fi

        if echo "$cfg_local" | grep -q "^${key} "; then
          continue
        fi

        printf '%s %s\n' "$key" "$val"
      done < "$pathf_cfg_common"
    fi
  )
${cfg_local}" > "$pathf_cfg"
else
  if [ -f "$pathf_cfg_common" ]; then
    cat "$pathf_cfg_common" > "$pathf_cfg"
  fi
fi

# Starting or reloading xsettingsd

killall -e "xsettingsd"
exec xsettingsd -c "$pathf_cfg"
