#!/usr/bin/env sh
#
# xscreensaver

## Starting or reloading xscreensaver

if [ "$(pidof xscreensaver)" ]; then 
  xscreensaver-command --restart 1>/dev/null 2>/dev/null & disown
else
  xscreensaver --no-splash 1>/dev/null 2>/dev/null & disown
fi

## Starting xss-lock

[ -z "$(pidof xss-lock)" ] && exec xss-lock --ignore-sleep -- xscreensaver-command -lock 1>/dev/null 2>/dev/null & disown
